"use client";

// @ts-nocheck - translations object contains intentional duplicate keys (last value wins at runtime)
import React, {
  createContext,
  useContext,
  useState,
  useEffect,
  ReactNode,
} from "react";

type Language = "en" | "am";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    const stored = localStorage.getItem("insa-buildms-language");
    if (stored === "am" || stored === "en") {
      setLanguageState(stored);
    }
  }, []);

  useEffect(() => {
    if (mounted) {
      localStorage.setItem("insa-buildms-language", language);
      // Update HTML lang attribute for accessibility
      document.documentElement.lang = language === "am" ? "am" : "en";
    }
  }, [language, mounted]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}

// ═══════════════════════════════════════════════════════════════════
// TRANSLATION DICTIONARIES
// ═══════════════════════════════════════════════════════════════════

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  en: {
    // ─────────────────────────────────────────────────────────────
    // Common / General
    // ─────────────────────────────────────────────────────────────
    "app.title": "INSA CMBMS",
    "app.subtitle":
      "INSA CMBMS unifies project approvals, space bookings, and maintenance workflows with full visibility and accountability.",


    "app.tagline": "Information Network Security Agency — Ethiopia",

    // ─────────────────────────────────────────────────────────────
    // Navigation
    // ─────────────────────────────────────────────────────────────
    "nav.dashboard": "Dashboard",
    "nav.projects": "Projects",
    "nav.bookings": "Space & Bookings",
    "nav.maintenance": "Maintenance",
    "nav.notifications": "Notifications",
    "nav.reports": "Reports & Analytics",
    "nav.users": "User Management",
    "nav.config": "System Config",
    "nav.allRequests": "All User Requests",

    // ─────────────────────────────────────────────────────────────
    // Authentication
    // ─────────────────────────────────────────────────────────────
    "auth.login": "Sign In",
    "auth.logout": "Sign Out",
    "auth.register": "Request Access",
    "auth.welcomeBack": "Welcome Back",
    "auth.securePortal": "Secure Access Portal",
    "auth.signInPrompt": "Sign in with your credentials to continue.",
    "auth.email": "Email Address",
    "auth.password": "Password",
    "auth.forgotPassword": "Forgot password?",
    "auth.signingIn": "Signing in...",
    "auth.demoQuickLogin": "Demo Quick Login",
    "auth.noAccount": "Don't have an account?",
    "auth.protectedBy": "Protected by Security Framework",
    "auth.loggedInAs": "Logged in as",

    // Roles
    "role.admin": "Admin",
    "role.user": "User",
    "role.technician": "Technician",

    // ─────────────────────────────────────────────────────────────
    // Module Labels
    // ─────────────────────────────────────────────────────────────
    "module.projects": "Projects & Design",
    "module.bookings": "Space Allocation & Booking",
    "module.maintenance": "Urgent Repairs & HVAC",

    // ─────────────────────────────────────────────────────────────
    // Status
    // ─────────────────────────────────────────────────────────────
    "status.pending": "Pending",
    "status.approved": "Approved",
    "status.rejected": "Rejected",
    "status.completed": "Completed",
    "status.inProgress": "In Progress",
    "status.scheduled": "Scheduled",
    "status.cancelled": "Cancelled",
    "status.onHold": "On Hold",

    // ─────────────────────────────────────────────────────────────
    // Priority
    // ─────────────────────────────────────────────────────────────
    "priority.low": "Low",
    "priority.medium": "Medium",
    "priority.high": "High",
    "priority.urgent": "Urgent",
    "priority.critical": "Critical",

    // ─────────────────────────────────────────────────────────────
    // Common Actions
    // ─────────────────────────────────────────────────────────────
    "action.submit": "Submit",
    "action.cancel": "Cancel",
    "action.save": "Save",
    "action.delete": "Delete",
    "action.edit": "Edit",
    "action.view": "View",
    "action.approve": "Approve",
    "action.reject": "Reject",
    "action.download": "Download",
    "action.export": "Export",
    "action.search": "Search",
    "action.filter": "Filter",
    "action.close": "Close",
    "action.back": "Back",
    "action.next": "Next",
    "action.viewAll": "View All",
    "action.viewDetails": "View Details",
    "action.collapse": "Collapse",

    // ─────────────────────────────────────────────────────────────
    // Form Fields
    // ─────────────────────────────────────────────────────────────
    "form.title": "Title",
    "form.description": "Description",
    "form.location": "Location",
    "form.date": "Date",
    "form.startDate": "Start Date",
    "form.endDate": "End Date",
    "form.category": "Category",
    "form.budget": "Budget",
    "form.status": "Status",
    "form.priority": "Priority",
    "form.assignedTo": "Assigned To",
    "form.createdBy": "Created By",
    "form.notes": "Notes",
    "form.attachments": "Attachments",
    "form.comments": "Comments",
    "form.type": "Type",
    "form.department": "Department",
    "form.phone": "Phone",
    "form.contact": "Contact",

    // ─────────────────────────────────────────────────────────────
    // Dashboard
    // ─────────────────────────────────────────────────────────────
    "dashboard.welcome": "Welcome back",
    "dashboard.overview": "Overview",
    "dashboard.statistics": "Statistics",
    "dashboard.recentActivity": "Recent Activity",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.myRequests": "My Requests",
    "dashboard.pendingApprovals": "Pending Approvals",
    "dashboard.totalRequests": "Total Requests",
    "dashboard.activeProjects": "Active Projects",
    "dashboard.openBookings": "Open Bookings",
    "dashboard.urgentIssues": "Urgent Issues",

    // ─────────────────────────────────────────────────────────────
    // Projects
    // ─────────────────────────────────────────────────────────────
    "projects.title": "Projects",
    "projects.newProject": "New Project",
    "projects.projectTitle": "Project Title",
    "projects.projectDescription": "Project Description",
    "projects.estimatedCost": "Estimated Cost",
    "projects.fundingSource": "Funding Source",
    "projects.designRequirements": "Design Requirements",
    "projects.allProjects": "All Projects",
    "projects.myProjects": "My Projects",
    "projects.viewProject": "View Project",
    "projects.projectDetails": "Project Details",
    "projects.timeline": "Timeline",
    "projects.milestones": "Milestones",

    // ─────────────────────────────────────────────────────────────
    // Bookings
    // ─────────────────────────────────────────────────────────────
    "bookings.title": "Space & Bookings",
    "bookings.newBooking": "New Booking",
    "bookings.spaceName": "Space Name",
    "bookings.purpose": "Purpose",
    "bookings.attendees": "Number of Attendees",
    "bookings.bookingDate": "Booking Date",
    "bookings.timeSlot": "Time Slot",
    "bookings.allBookings": "All Bookings",
    "bookings.myBookings": "My Bookings",
    "bookings.upcomingBookings": "Upcoming Bookings",
    "bookings.availableSpaces": "Available Spaces",

    // ─────────────────────────────────────────────────────────────
    // Maintenance
    // ─────────────────────────────────────────────────────────────
    "maintenance.title": "Maintenance & Repairs",
    "maintenance.newRequest": "New Maintenance Request",
    "maintenance.issueType": "Issue Type",
    "maintenance.issueDescription": "Issue Description",
    "maintenance.affectedArea": "Affected Area",
    "maintenance.urgencyLevel": "Urgency Level",
    "maintenance.allRequests": "All Requests",
    "maintenance.myRequests": "My Requests",
    "maintenance.assignedToMe": "Assigned to Me",
    "maintenance.requestDetails": "Request Details",

    // ─────────────────────────────────────────────────────────────
    // Notifications
    // ─────────────────────────────────────────────────────────────
    "notifications.title": "Notifications",
    "notifications.unread": "unread",
    "notifications.markAllRead": "Mark All as Read",
    "notifications.noNotifications": "No notifications",
    "notifications.viewAll": "View all notifications →",

    // ─────────────────────────────────────────────────────────────
    // Reports
    // ─────────────────────────────────────────────────────────────
    "reports.title": "Reports & Analytics",
    "reports.generate": "Generate Report",
    "reports.exportData": "Export Data",
    "reports.dateRange": "Date Range",
    "reports.reportType": "Report Type",

    // ─────────────────────────────────────────────────────────────
    // Users
    // ─────────────────────────────────────────────────────────────
    "users.title": "User Management",
    "users.addUser": "Add User",
    "users.name": "Name",
    "users.email": "Email",
    "users.role": "Role",
    "users.department": "Department",
    "users.status": "Status",
    "users.active": "Active",
    "users.inactive": "Inactive",

    // ─────────────────────────────────────────────────────────────
    // Messages & Placeholders
    // ─────────────────────────────────────────────────────────────
    "message.noData": "No data available",
    "message.loading": "Loading...",
    "message.error": "An error occurred",
    "message.success": "Operation completed successfully",
    "message.confirmDelete": "Are you sure you want to delete this?",
    "placeholder.search": "Search requests, IDs...",
    "placeholder.selectDate": "Select date",
    "placeholder.enterText": "Enter text...",

    // ─────────────────────────────────────────────────────────────
    // Additional Dashboard
    // ─────────────────────────────────────────────────────────────
    "dashboard.systemHealth": "System Health",
    "dashboard.kpiMetrics": "KPI Metrics",
    "dashboard.activityLog": "Activity Log",
    "dashboard.viewDashboard": "View Dashboard",
    "dashboard.noActivity": "No recent activity",
    "dashboard.averageCompletionTime": "Avg. Completion Time",
    "dashboard.days": "days",

    // ─────────────────────────────────────────────────────────────
    // Admin Dashboard
    // ─────────────────────────────────────────────────────────────
    "admin.masterControl": "Admin Master Control Layer",
    "admin.systemOverview": "System Overview",
    "admin.requestsAwaitingAction": "Requests Awaiting Action",
    "admin.noRequestsAwaitingAction": "No requests awaiting action",
    "admin.requestID": "Request ID",
    "admin.submittedBy": "Submitted By",
    "admin.viewAllRequests": "View All Requests",
    "admin.allUserRequests": "All User Requests",
    "admin.systemConfig": "System Configuration",
    "admin.across": "Across",
    "admin.modules": "Modules",

    // ─────────────────────────────────────────────────────────────
    // Projects - Extended
    // ─────────────────────────────────────────────────────────────
    "projects.submitProject": "Submit Project",
    "projects.projectID": "Project ID",
    "projects.submittedOn": "Submitted On",
    "projects.noProjects": "No projects found",
    "projects.filterByStatus": "Filter by Status",
    "projects.allStatuses": "All Statuses",
    "projects.requestDetails": "Request Details",
    "projects.budgetInfo": "Budget Information",
    "projects.attachedDocuments": "Attached Documents",
    "projects.noDocuments": "No documents attached",
    "projects.adminActions": "Admin Actions",
    "projects.approveProject": "Approve Project",
    "projects.rejectProject": "Reject Project",
    "projects.statusHistory": "Status History",
    "projects.addNote": "Add Note",
    "projects.internalNotes": "Internal Notes",
    "projects.noNotes": "No notes yet",
    "projects.projectApproved": "Project approved successfully",
    "projects.projectRejected": "Project rejected",
    "projects.estimatedBudget": "Estimated Budget",
    "projects.actualCost": "Actual Cost",
    "projects.costVariance": "Cost Variance",
    "projects.enterProjectDetails": "Enter project details below",
    "projects.enterTitle": "Enter project title",
    "projects.enterDescription": "Enter detailed project description",
    "projects.enterLocation": "Enter project location",
    "projects.enterEstimatedCost": "Enter estimated cost in ETB",
    "projects.enterFundingSource": "Enter funding source",
    "projects.enterDesignRequirements": "Specify design requirements",
    "projects.reviewAndSubmit": "Review and Submit",

    // ─────────────────────────────────────────────────────────────
    // Bookings - Extended
    // ─────────────────────────────────────────────────────────────
    "bookings.submitBooking": "Submit Booking",
    "bookings.bookingID": "Booking ID",
    "bookings.bookedOn": "Booked On",
    "bookings.noBookings": "No bookings found",
    "bookings.requestedBy": "Requested By",
    "bookings.bookingDetails": "Booking Details",
    "bookings.approveBooking": "Approve Booking",
    "bookings.rejectBooking": "Reject Booking",
    "bookings.bookingApproved": "Booking approved successfully",
    "bookings.bookingRejected": "Booking rejected",
    "bookings.enterBookingDetails": "Enter booking details below",
    "bookings.enterSpaceName": "Enter space name",
    "bookings.enterPurpose": "Enter purpose of booking",
    "bookings.enterAttendees": "Enter number of attendees",
    "bookings.selectBookingDate": "Select booking date",
    "bookings.selectTimeSlot": "Select time slot",
    "bookings.morningSlot": "Morning (8:00 AM - 12:00 PM)",
    "bookings.afternoonSlot": "Afternoon (1:00 PM - 5:00 PM)",
    "bookings.eveningSlot": "Evening (5:00 PM - 9:00 PM)",
    "bookings.fullDaySlot": "Full Day (8:00 AM - 5:00 PM)",
    "bookings.spaceType": "Space Type",
    "bookings.conferenceRoom": "Conference Room",
    "bookings.trainingHall": "Training Hall",
    "bookings.laboratory": "Laboratory",
    "bookings.office": "Office",
    "bookings.otherSpace": "Other",

    // ─────────────────────────────────────────────────────────────
    // Maintenance - Extended
    // ─────────────────────────────────────────────────────────────
    "maintenance.submitRequest": "Submit Request",
    "maintenance.requestID": "Request ID",
    "maintenance.reportedOn": "Reported On",
    "maintenance.noRequests": "No maintenance requests found",
    "maintenance.reportedBy": "Reported By",
    "maintenance.assignTechnician": "Assign Technician",
    "maintenance.selectTechnician": "Select a technician",
    "maintenance.updateStatus": "Update Status",
    "maintenance.markRepaired": "Mark as Repaired",
    "maintenance.markCompleted": "Mark as Completed",
    "maintenance.statusUpdated": "Status updated successfully",
    "maintenance.technicianAssigned": "Technician assigned successfully",
    "maintenance.workLog": "Work Log",
    "maintenance.addWorkNote": "Add Work Note",
    "maintenance.enterWorkNote": "Enter work note",
    "maintenance.noWorkLogs": "No work logs yet",
    "maintenance.enterMaintenanceDetails":
      "Enter maintenance request details below",
    "maintenance.selectIssueType": "Select issue type",
    "maintenance.hvacIssue": "HVAC",
    "maintenance.electricalIssue": "Electrical",
    "maintenance.plumbingIssue": "Plumbing",
    "maintenance.structuralIssue": "Structural",
    "maintenance.generalIssue": "General Maintenance",
    "maintenance.enterIssueDescription": "Describe the issue in detail",
    "maintenance.enterAffectedArea": "Specify affected area/location",
    "maintenance.selectUrgency": "Select urgency level",
    "maintenance.assignedTechnician": "Assigned Technician",
    "maintenance.unassigned": "Unassigned",
    "maintenance.estimatedTime": "Estimated Time",
    "maintenance.repairCost": "Repair Cost",

    // ─────────────────────────────────────────────────────────────
    // Notifications - Extended
    // ─────────────────────────────────────────────────────────────
    "notifications.allNotifications": "All Notifications",
    "notifications.readNotifications": "Read Notifications",
    "notifications.unreadNotifications": "Unread Notifications",
    "notifications.clearAll": "Clear All",
    "notifications.noUnreadNotifications": "No unread notifications",
    "notifications.today": "Today",
    "notifications.yesterday": "Yesterday",
    "notifications.thisWeek": "This Week",
    "notifications.older": "Older",

    // ─────────────────────────────────────────────────────────────
    // Reports - Extended
    // ─────────────────────────────────────────────────────────────
    "reports.systemReports": "System Reports & Analytics",
    "reports.projectsReport": "Projects Report",
    "reports.bookingsReport": "Bookings Report",
    "reports.maintenanceReport": "Maintenance Report",
    "reports.usersReport": "Users Report",
    "reports.exportPDF": "Export PDF",
    "reports.exportExcel": "Export Excel",
    "reports.exportCSV": "Export CSV",
    "reports.selectReportType": "Select report type",
    "reports.selectDateRange": "Select date range",
    "reports.from": "From",
    "reports.to": "To",
    "reports.last7Days": "Last 7 Days",
    "reports.last30Days": "Last 30 Days",
    "reports.last90Days": "Last 90 Days",
    "reports.customRange": "Custom Range",
    "reports.totalProjects": "Total Projects",
    "reports.totalBookings": "Total Bookings",
    "reports.totalMaintenanceRequests": "Total Maintenance Requests",
    "reports.completionRate": "Completion Rate",
    "reports.averageResolutionTime": "Average Resolution Time",
    "reports.projectsByStatus": "Projects by Status",
    "reports.bookingsByStatus": "Bookings by Status",
    "reports.maintenanceByPriority": "Maintenance by Priority",
    "reports.trendAnalysis": "Trend Analysis",
    "reports.performanceMetrics": "Performance Metrics",

    // ─────────────────────────────────────────────────────────────
    // Users Management - Extended
    // ─────────────────────────────────────────────────────────────
    "users.allUsers": "All Users",
    "users.addNewUser": "Add New User",
    "users.editUser": "Edit User",
    "users.deleteUser": "Delete User",
    "users.userDetails": "User Details",
    "users.fullName": "Full Name",
    "users.emailAddress": "Email Address",
    "users.phoneNumber": "Phone Number",
    "users.userRole": "User Role",
    "users.selectRole": "Select role",
    "users.selectDepartment": "Select department",
    "users.accountStatus": "Account Status",
    "users.activateUser": "Activate User",
    "users.deactivateUser": "Deactivate User",
    "users.resetPassword": "Reset Password",
    "users.lastLogin": "Last Login",
    "users.createdOn": "Created On",
    "users.noUsers": "No users found",
    "users.searchUsers": "Search users",
    "users.filterByRole": "Filter by Role",
    "users.filterByStatus": "Filter by Status",
    "users.userCreated": "User created successfully",
    "users.userUpdated": "User updated successfully",
    "users.userDeleted": "User deleted successfully",
    "users.confirmDeleteUser": "Are you sure you want to delete this user?",

    // ─────────────────────────────────────────────────────────────
    // System Config - Extended
    // ─────────────────────────────────────────────────────────────
    "config.title": "System Configuration",
    "config.generalSettings": "General Settings",
    "config.emailSettings": "Email Settings",
    "config.notificationSettings": "Notification Settings",
    "config.slaSettings": "SLA Settings",
    "config.workflowSettings": "Workflow Settings",
    "config.systemName": "System Name",
    "config.timezone": "Timezone",
    "config.language": "Default Language",
    "config.dateFormat": "Date Format",
    "config.saveSettings": "Save Settings",
    "config.settingsSaved": "Settings saved successfully",
    "config.emailNotifications": "Email Notifications",
    "config.smsNotifications": "SMS Notifications",
    "config.pushNotifications": "Push Notifications",
    "config.enableNotifications": "Enable Notifications",
    "config.disableNotifications": "Disable Notifications",

    // ─────────────────────────────────────────────────────────────
    // Auth - Extended
    // ─────────────────────────────────────────────────────────────
    "auth.createAccount": "Create Account",
    "auth.haveAccount": "Already have an account?",
    "auth.signIn": "Sign in",
    "auth.fullName": "Full Name",
    "auth.confirmPassword": "Confirm Password",
    "auth.agreeToTerms": "I agree to the Terms and Conditions",
    "auth.resetPassword": "Reset Password",
    "auth.backToLogin": "Back to Login",
    "auth.sendResetLink": "Send Reset Link",
    "auth.resetLinkSent": "Reset link sent to your email",
    "auth.enterEmailForReset":
      "Enter your email address to receive a password reset link",
    "auth.registrationRequest": "Registration Request",
    "auth.requestAccessDesc": "Request access to the INSA CMBMS system",
    "auth.department": "Department",
    "auth.position": "Position",
    "auth.reason": "Reason for Access",
    "auth.submitRequest": "Submit Request",
    "auth.requestSubmitted": "Request submitted successfully",

    // ─────────────────────────────────────────────────────────────
    // Common UI Elements
    // ─────────────────────────────────────────────────────────────
    "common.showing": "Showing",
    "common.of": "of",
    "common.results": "results",
    "common.page": "Page",
    "common.previous": "Previous",
    "common.next": "Next",
    "common.rowsPerPage": "Rows per page",
    "common.selectAll": "Select All",
    "common.deselectAll": "Deselect All",
    "common.selected": "selected",
    "common.bulkActions": "Bulk Actions",
    "common.refresh": "Refresh",
    "common.print": "Print",
    "common.share": "Share",
    "common.copy": "Copy",
    "common.copied": "Copied!",
    "common.copyToClipboard": "Copy to Clipboard",
    "common.yes": "Yes",
    "common.no": "No",
    "common.confirm": "Confirm",
    "common.required": "Required",
    "common.optional": "Optional",
    "common.all": "All",
    "common.none": "None",
    "common.or": "or",
    "common.and": "and",

    // Greetings
    "greeting.morning": "Good Morning",
    "greeting.afternoon": "Good Afternoon",
    "greeting.evening": "Good Evening",

    // Dashboard - Extended
    "dashboard.trackRequests": "Track your requests, bookings, and maintenance",
    "dashboard.assignedTasksQueue": "Your assigned tasks and maintenance queue",
    "dashboard.myProjects": "My Projects",
    "dashboard.myBookings": "My Bookings",
    "dashboard.myMaintenance": "My Maintenance",
    "dashboard.unreadAlerts": "Unread Alerts",
    "dashboard.assignedTasks": "Assigned Tasks",
    "dashboard.activeRepairs": "Active Repairs",
    "dashboard.completedTasks": "Completed",
    "dashboard.currentlyWorking": "Currently working",
    "dashboard.totalAssigned": "Total assigned",
    "dashboard.thisMonth": "This month",
    "dashboard.unreadAlertsNotif": "Unread alerts",
    "dashboard.notifications": "Notifications",
    "dashboard.inProgress": "in progress",
    "dashboard.confirmed": "confirmed",
    "dashboard.resolved": "resolved",
    "dashboard.submitProjectRequest": "Submit Project Request",
    "dashboard.bookASpace": "Book a Space",
    "dashboard.reportMaintenance": "Report Maintenance",
    "dashboard.criticalAlerts": "Critical Alerts",
    "dashboard.noCriticalAlerts": "No critical alerts",
    "dashboard.upcomingBookings": "Upcoming Bookings",
    "dashboard.attendees": "attendees",

    // Projects - Page Specific
    "projects.streamA": "Stream A",
    "projects.projectsFound": "project(s) found",
    "projects.newProjectRequest": "New Project Request",
    "projects.searchByTitleOrID": "Search by title or ID...",
    "projects.classification": "Classification",
    "projects.budgetETB": "Budget (ETB)",
    "projects.updated": "Updated",
    "projects.actions": "Actions",
    "projects.noProjectsFound": "No Projects Found",
    "projects.tryAdjusting": "Try adjusting your search or filters",
    "projects.submitFirstRequest": "Submit First Request",
    "projects.review": "Review",
    "projects.workflowProgress": "Workflow Progress",
    "projects.projectNotFound": "Project not found",
    "projects.backToProjects": "← Back to Projects",
    "projects.description": "Project Description",
    "projects.notYetAssigned": "Not yet assigned",
    "projects.activityTimeline": "Activity Timeline",
    "projects.documents": "Documents",
    "projects.noDocumentsAttached": "No documents attached",
    "projects.download": "Download",
    "projects.startReview": "Start Review",
    "projects.markInProgress": "Mark In Progress",
    "projects.markCompleted": "Mark Completed",
    "projects.assignProfessional": "Assign Professional",
    "projects.selectStaff": "Select staff...",
    "projects.sendToRequester": "Send to Requester",
    "projects.quickInfo": "Quick Info",
    "projects.created": "Created",
    "projects.lastUpdated": "Last Updated",
    "projects.filesCount": "file(s)",
    "projects.timelineEventsCount": "Timeline Events",
    "projects.actionApplied": "Action applied",
    "projects.addCommentOrReason": "Add a comment or reason...",

    // Bookings - Page Specific
    "bookings.spaceAllocation": "Space Allocation & Booking",
    "bookings.bookingsCount": "booking(s)",
    "bookings.list": "List",
    "bookings.calendar": "Calendar",
    "bookings.spaces": "Spaces",
    "bookings.addSpace": "Add Space",
    "bookings.searchBookings": "Search bookings...",
    "bookings.noBookingsFound": "No Bookings Found",
    "bookings.noBookingsMatch": "No bookings match your filters",
    "bookings.requirements": "Requirements",
    "bookings.totalSpaces": "Total Spaces",
    "bookings.availableSpacesCount": "Available",
    "bookings.occupiedSpaces": "Occupied",
    "bookings.searchSpaces": "Search spaces...",
    "bookings.allTypes": "All Types",
    "bookings.editSpace": "Edit Space",
    "bookings.addNewSpace": "Add New Space",
    "bookings.spaceName_label": "Space Name *",
    "bookings.spaceType_label": "Space Type *",
    "bookings.capacity_label": "Capacity *",
    "bookings.floorLocation": "Floor / Location *",
    "bookings.availabilityStatus": "Availability Status",
    "bookings.available_btn": "Available",
    "bookings.occupied_btn": "Occupied",
    "bookings.saveChanges": "Save Changes",
    "bookings.deleteSpace": "Delete Space?",
    "bookings.deleteSpaceWarning":
      "This action cannot be undone. Active bookings linked to this space may be affected.",
    "bookings.yesDelete": "Yes, Delete",
    "bookings.noBookingType": "New Request",
    "bookings.officeSpaceAllocation": "Office Space Allocation",
    "bookings.sharedHallBooking": "Shared Hall / Room Booking",
    "bookings.selectRequestType": "Select Request Type",
    "bookings.reviewAndConfirm": "Review & Confirm",
    "bookings.allocationSubmitted": "Allocation Request Submitted!",
    "bookings.bookingSubmitted": "Booking Submitted!",
    "bookings.viewBookings": "View Bookings",

    // Bookings - Additional keys
    "bookings.confirmDeleteText": "You are about to permanently delete:",
    "bookings.noSpacesFound": "No Spaces Found",
    "bookings.tryAdjustFilters": "Try adjusting your search or filters",
    "bookings.addFirstSpace": "Add First Space",
    "bookings.seats": "seats",
    "bookings.bookNow": "Book Now",
    "bookings.currentlyBooked": "Currently Booked",
    "bookings.step.classification": "Classification",
    "bookings.step.officeDetails": "Office Details",
    "bookings.step.staffingReqs": "Staffing & Requirements",
    "bookings.step.review": "Review",
    "bookings.step.selectSpace": "Select Space",
    "bookings.step.dateTime": "Date & Time",
    "bookings.step.eventDetails": "Event Details",
    "bookings.allocationBeingReviewed":
      "Your office space allocation request is being reviewed by the Space Manager.",
    "bookings.hallPendingApproval":
      "Your hall booking request is under review.",
    "bookings.generatedAllocationID": "Generated Allocation ID",
    "bookings.generatedBookingID": "Generated Booking ID",
    "bookings.officeAllocationDetails": "Office Allocation Details",
    "bookings.requestingDeptReq": "Requesting Department *",
    "bookings.contactPersonReq": "Contact Person *",
    "bookings.contactPhoneReq": "Contact Phone *",
    "bookings.reasonForAllocReq": "Reason for Allocation *",
    "bookings.officeTypePrefReq": "Office Type Preference *",
    "bookings.preferredLocationOpt": "Preferred Location (optional)",
    "bookings.staffingDataTitle": "Staffing Data & Special Requirements",
    "bookings.seniorStaffCount": "Senior Staff Count *",
    "bookings.supportStaffCount": "Support Staff Count",
    "bookings.totalHeadcountLabel": "Total headcount:",
    "bookings.people": "people",
    "bookings.specialReqsLabel": "Special Requirements",
    "bookings.additionalNotesLabel": "Additional Notes",
    "bookings.selectASpace": "Select a Space",
    "bookings.available_dot": "● Available",
    "bookings.booked_dot": "● Booked",
    "bookings.capacityCap": "cap.",
    "bookings.conflictDetected":
      "⚠️ Conflict detected! This space is already booked for the selected date/time.",
    "bookings.dateReq": "Date *",
    "bookings.startTimeReq": "Start Time *",
    "bookings.endTimeReq": "End Time *",
    "bookings.selectedSpaceLabel": "Selected:",
    "bookings.capacityDetailLabel": "Capacity:",
    "bookings.eventMeetingTitle": "Event / Meeting Title *",
    "bookings.purposeReq": "Purpose *",
    "bookings.numAttendeesReq": "Number of Attendees *",
    "bookings.capacityUsed": "Capacity used",
    "bookings.roomLayoutLabel": "Room Layout",
    "bookings.requiredAmenities": "Required Amenities",
    "bookings.reviewConfirmH2": "Review & Confirm",
    "bookings.b1RequestType": "B1 – Office Space Allocation",
    "bookings.b2RequestType": "B2 – Shared Hall Booking",
    "bookings.requestTypeKey": "Request Type",
    "bookings.reasonKey": "Reason",
    "bookings.officeTypeKey": "Office Type",
    "bookings.seniorStaffKey": "Senior Staff",
    "bookings.supportStaffKey": "Support Staff",
    "bookings.totalHeadcountKey": "Total Headcount",
    "bookings.specialReqsKey": "Special Requirements",
    "bookings.preferredLocationKey": "Preferred Location",
    "bookings.noPreference": "No preference",
    "bookings.spaceKey": "Space",
    "bookings.timeKey": "Time",
    "bookings.eventTitleKey": "Title",
    "bookings.attendeesKey": "Attendees",
    "bookings.layoutKey": "Layout",
    "bookings.amenitiesKey": "Amenities",
    "bookings.notSpecified": "Not specified",
    "bookings.noneText": "None",
    "bookings.confirmAndSubmit": "Confirm & Submit",
    "bookings.continueBtn": "Continue",
    "bookings.b1CardTitle": "Office Space Allocation",
    "bookings.b1CardDesc":
      "Request office space for new hires, team expansion, or relocation. Routed to Space Manager.",
    "bookings.b2CardTitle": "Shared Hall / Room Booking",
    "bookings.b2CardDesc":
      "Book conference halls, training rooms, labs. Conflict detection included. Routed to Hall Officer & IT.",

    // Reports - Additional
    "reports.trendPlusTwo": "+2 this month",
    "reports.trendMTTR": "-3h vs last",
    "reports.trendBudget": "+12%",
    "reports.trendBookings": "+5 this week",

    // Users - Additional
    "users.locked": "Locked",

    // All Requests - Additional
    "requests.needsAttention": "Needs Attention",
    "requests.adminNote": "Admin Note to Requester",
    "requests.adminNotePlaceholder":
      "Write a note, feedback, or clarification request...",
    "requests.noteSent": "Note sent to requester",
    "requests.sendNote": "Send Note",
    "requests.openFullDetail": "Open Full Detail",
    "requests.allUsersOption": "All Users",
    "requests.requester": "Requester",
    "requests.sortModule": "Module",
    "requests.requestsCount": "requests",
    "requests.filtersBtn": "Filters",
    "requests.sortDate": "Date",
    "requests.sortStatus": "Status",
    "requests.sortRequester": "Requester",

    // Config - Additional
    "config.streamA": "A – Projects",
    "config.streamB": "B – Bookings",
    "config.streamC": "C – Maintenance",
    "config.addStatus": "Add Status",
    "config.saveChanges": "Save Changes",
    "config.priorityLevelConfig": "Priority Level Configuration",
    "config.slaTarget": "SLA Target:",
    "config.colorLabel": "Color",
    "config.savePrioritySettings": "Save Priority Settings",
    "config.addTemplate": "Add Template",
    "config.saveAllTemplates": "Save All Templates",
    "config.featureToggles": "Feature Toggles",
    "config.adminEmail": "Admin Email",
    "config.maxFileSize": "Max File Size (MB)",
    "config.sessionTimeout": "Session Timeout (hours)",
    "config.saveGeneralSettings": "Save General Settings",
    "config.saveFeatureSettings": "Save Feature Settings",
    "config.enableInAppNotif": "Enable In-App Notifications",
    "config.showNotifBellDesc": "Show notification bell and alerts",
    "config.enableEmailAlerts": "Enable Email Alerts",
    "config.sendEmailStatusDesc": "Send email on status changes",
    "config.enableSMSAlerts": "Enable SMS Alerts",
    "config.sendSMSCriticalDesc": "Send SMS for critical events",
    "config.autoAssignTech": "Auto-Assign Technicians",
    "config.autoAssignDesc": "Automatically assign based on availability",
    "config.requireBudgetProj": "Require Budget for Projects",
    "config.requireBudgetDesc": "Make budget field mandatory",

    // Maintenance - Page Specific
    "maintenance.urgentRepairsHVAC": "Urgent Repairs & HVAC",
    "maintenance.maintenanceAndRepairs": "Maintenance & Repairs",
    "maintenance.ticketsCount": "ticket(s)",
    "maintenance.kanban": "Kanban",
    "maintenance.list": "List",
    "maintenance.newRequest_btn": "New Request",
    "maintenance.noTickets": "No tickets",
    "maintenance.noTicketsFound": "No Tickets Found",
    "maintenance.noTicketsMatch": "No maintenance tickets match your filters",
    "maintenance.assignTech": "+ Assign Technician",
    "maintenance.assignTechBtn": "Assign Tech",
    "maintenance.selectTechOption": "Select tech...",
    "maintenance.viewDetails": "View Details",
    "maintenance.submitMaintenanceRequest": "Submit Maintenance Request",
    "maintenance.selectMaintenanceClassification":
      "Select Maintenance Classification",
    "maintenance.urgentRepairsClass": "Urgent Repairs",
    "maintenance.hvacMaintenance": "HVAC & AC Maintenance",
    "maintenance.issueTitle": "Issue Title *",
    "maintenance.repairType": "Repair Type",
    "maintenance.hvacServiceType": "HVAC Service Type",
    "maintenance.priorityLevel": "Priority Level",
    "maintenance.problemDescription": "Problem Description *",
    "maintenance.suspectedParts": "Suspected Parts Needed",
    "maintenance.costEstimation": "Cost Estimation (optional)",
    "maintenance.locationContact": "Location & Contact Details",
    "maintenance.buildingBlock": "Building / Block *",
    "maintenance.floor_field": "Floor *",
    "maintenance.roomOfficeNo": "Room / Office No.",
    "maintenance.contactPerson": "Contact Person",
    "maintenance.contactPhone": "Contact Phone *",
    "maintenance.additionalNotes": "Additional Notes",
    "maintenance.attachPhotos": "Attach Photos / Documents",
    "maintenance.dragDropPhotos": "Drag & drop photos here",
    "maintenance.reviewAndSubmit": "Review & Submit",
    "maintenance.requestSubmitted_title": "Request Submitted!",
    "maintenance.autoAssignedTo": "Auto-assigned to:",
    "maintenance.viewMaintenance": "View Maintenance",
    "maintenance.goToDashboard": "Go to Dashboard",
    "maintenance.maintenanceWorkflow": "Maintenance Workflow",
    "maintenance.ticketDetails": "Ticket Details",
    "maintenance.location_label": "Location",
    "maintenance.floor_label": "Floor",
    "maintenance.reportedBy_label": "Reported By",
    "maintenance.assignedTo_label": "Assigned To",
    "maintenance.notAssigned": "Not assigned",
    "maintenance.created_label": "Created",
    "maintenance.resolved_label": "Resolved",
    "maintenance.pending_label": "Pending",
    "maintenance.attachments_label": "Attachments",
    "maintenance.noAttachments": "No attachments",
    "maintenance.uploadRepairProof": "Upload Repair Proof / Completion Photo",
    "maintenance.repairCostTracking": "Repair Cost Tracking",
    "maintenance.materialsCost": "Materials Cost (ETB)",
    "maintenance.laborCostETB": "Labor Cost (ETB)",
    "maintenance.partsUsed": "Parts / Materials Used",
    "maintenance.totalRepairCost": "Total Repair Cost",
    "maintenance.saveCostData": "Save Cost Data",
    "maintenance.activityTimeline": "Activity Timeline",
    "maintenance.adminActions_label": "Admin Actions",
    "maintenance.assignAndNotify": "Assign & Notify",
    "maintenance.verifyAndClose": "Verify & Close Ticket",
    "maintenance.saveNote": "Save Note",
    "maintenance.technicianNote": "Technician Note",
    "maintenance.startRepair": "Start Repair",
    "maintenance.markAsRepaired": "Mark as Repaired",
    "maintenance.confirmCompletion": "Confirm Completion",
    "maintenance.confirmIssueResolved": "✓ Confirm Issue Resolved",
    "maintenance.ticketVerifyDesc":
      "The technician has marked this issue as repaired. Please verify and confirm.",
    "maintenance.ticketInfo": "Ticket Info",
    "maintenance.ticketID": "Ticket ID",
    "maintenance.timelineEvents_label": "Timeline Events",
    "maintenance.attachmentsCount": "Attachments",
    "maintenance.totalCost": "Total Cost",
    "maintenance.ticketNotFound": "Ticket not found",
    "maintenance.costDataSaved": "Cost data saved successfully",

    // Notifications - Page Specific
    "notifications.allCaughtUp": "All caught up!",
    "notifications.allFilter": "all",
    "notifications.unreadFilter": "unread",
    "notifications.readFilter": "read",
    "notifications.markRead": "Mark read",
    "notifications.noUnreadFound": "No Unread Notifications",
    "notifications.noNotificationsFound": "No Notifications Found",
    "notifications.youreAllCaughtUp": "You're all caught up!",
    "notifications.total": "Total",
    "notifications.read": "Read",

    // Reports - Page Specific
    "reports.reportsAndAnalytics": "Reports & Analytics",
    "reports.systemWidePerformance":
      "System-wide performance metrics, cost tracking, and maintenance insights",
    "reports.totalProjects_label": "Total Projects",
    "reports.avgMTTR": "Avg MTTR (hrs)",
    "reports.totalBudgetETB": "Total Budget (ETB)",
    "reports.confirmedBookings_label": "Approved Bookings",
    "reports.preventiveMaintSchedules":
      "Preventive Maintenance Schedule(s) Overdue",
    "reports.reviewAndDispatch":
      "Review the Preventive Maintenance Schedule below and dispatch technicians immediately.",
    "reports.requestVolumeOverTime": "Request Volume Over Time",
    "reports.monthlyBreakdown": "Monthly breakdown by module",
    "reports.requestStatusDist": "Request Status Distribution",
    "reports.overallCompletionRates": "Overall completion and pending rates",
    "reports.meanTimeToRepair": "Mean Time to Repair (MTTR)",
    "reports.avgHoursToResolve":
      "Average hours to resolve maintenance tickets per month",
    "reports.spaceUtilizationRate": "Space Utilization Rate",
    "reports.bookingFrequency": "Booking frequency by space (%)",
    "reports.budgetVsActual": "Budget vs Actual Cost Tracking (ETB)",
    "reports.plannedVsActual": "Planned vs actual expenditure per month",
    "reports.repairCostPerTicket": "Repair Cost per Maintenance Ticket (ETB)",
    "reports.materialsLaborBreakdown":
      "Materials + labor breakdown per closed ticket",
    "reports.teamPerformance": "Maintenance Team Performance",
    "reports.multiDimensional":
      "Multi-dimensional technician performance radar",
    "reports.technicianKPIs": "Technician KPIs",
    "reports.individualPerformance":
      "Individual performance summary this period",
    "reports.completionRate_label": "Completion rate",
    "reports.preventiveMaintenanceSched": "Preventive Maintenance Schedule",
    "reports.recurringSystemMaint":
      "Recurring system maintenance (e.g. HVAC every 3 months, Elevator every 6 months)",
    "reports.performanceSummary": "Performance Summary",
    "reports.system_equipment": "System / Equipment",
    "reports.frequency": "Frequency",
    "reports.lastDone": "Last Done",
    "reports.nextDue": "Next Due",
    "reports.assignee": "Assignee",
    "reports.metric": "Metric",
    "reports.capitalProjects": "Projects",
    "reports.spaceAndBooking": "Space & Booking",
    "reports.maintenance_col": "Maintenance",
    "reports.total_col": "Total",
    "reports.totalRequests_row": "Total Requests",
    "reports.completedConfirmed": "Completed / Approved",
    "reports.pendingOpen": "Submitted / Open",
    "reports.rejectedCancelled": "Rejected / Closed",
    "reports.satisfaction": "satisfaction",
    "reports.assigned": "Assigned",
    "reports.completed": "Completed",

    // Users - Page Specific
    "users.usersCount": "user(s)",
    "users.active_count": "active",
    "users.administrators": "Administrators",
    "users.standardUsers": "Standard Users",
    "users.technicians": "Technicians",
    "users.user_col": "User",
    "users.id_col": "ID",
    "users.department_col": "Department",
    "users.role_col": "Role",
    "users.status_col": "Status",
    "users.joined_col": "Joined",
    "users.actions_col": "Actions",
    "users.edit_btn": "Edit",
    "users.disable_btn": "Disable",
    "users.enable_btn": "Enable",
    "users.createNewUser": "Create New User",
    "users.allRoles": "All Roles",
    "users.allStatuses": "All Statuses",
    "users.searchByNameEmailID": "Search by name, email, or ID...",
    "users.phone_label": "Phone",
    "users.department_label": "Department",
    "users.role_label": "Role *",
    "users.status_label": "Status",
    "users.saveChanges_btn": "Save Changes",
    "users.createUser_btn": "Create User",
    "users.showing": "Showing",
    "users.of": "of",
    "users.users": "users",

    // Admin Dashboard - Extended
    "admin.masterControlLayer": "Master Control Layer",
    "admin.systemAdministrator": "System Administrator",
    "admin.criticalAlert": "Critical Alert",
    "admin.criticalAlerts_multi": "Critical Alerts",
    "admin.pendingActions": "Pending Actions",
    "admin.overview": "Overview",
    "admin.analytics": "Analytics",
    "admin.workflow": "Workflow",
    "admin.activeUsers": "Active Users",
    "admin.pendingReviews": "Pending Reviews",
    "admin.projectsAwaitingAction": "Projects awaiting action",
    "admin.spaceRequests": "Space Requests",
    "admin.pendingApproval": "Pending approval",
    "admin.openTickets": "Open Tickets",
    "admin.slaCompliance": "SLA Compliance",
    "admin.ticketsResolvedOnTime": "Tickets resolved on time",
    "admin.totalBudget": "Total Budget",
    "admin.etbAcrossProjects": "ETB across all projects",
    "admin.adminControlPanel": "Admin Control Panel",
    "admin.navigateToKeyAreas": "Navigate to key management areas",
    "admin.moduleOversight": "Module Oversight",
    "admin.statusAcrossStreams": "Status across all three operational streams",
    "admin.systemWideActivity": "System-Wide Activity",
    "admin.fullReport": "Full Report",
    "admin.technicianWorkload": "Technician Workload",
    "admin.manageUsers": "Manage Users",
    "admin.userDistribution": "User Distribution",
    "admin.allClear": "All clear",
    "admin.workflowAlerts": "Workflow Alerts",
    "admin.awaitingReview": "Awaiting review",
    "admin.unassignedTicket": "Unassigned ticket",
    "admin.spaceBookingPending": "Space booking under review",
    "admin.reviewBtn": "Review",
    "admin.assignBtn": "Assign",
    "admin.approveBtn": "Approve",
    "admin.noActionsNeeded": "No pending workflow actions",
    "admin.onTrack": "On track",
    "admin.belowTarget": "Below target",
    "admin.ok": "OK",
    "admin.urgent": "Urgent",
    "admin.high": "High",
    "admin.normal": "Normal",

    // Config Page - Extended
    "config.statusManagement": "Status Management",
    "config.priorityLevels": "Priority Levels",
    "config.notificationTemplates": "Notification Templates",
    "config.systemSettings": "System Settings",
    "config.manageSettings":
      "Manage system settings, statuses, and notification templates",
    "config.savedSuccess": "settings saved successfully",

    // All Requests Page
    "requests.allUserRequests": "All User Requests",
    "requests.unifiedView":
      "Unified view of all submitted requests across modules",
    "requests.searchRequests": "Search by title, ID, or requester...",
    "requests.allModules": "All Modules",
    "requests.noRequestsFound": "No Requests Found",
    "requests.noRequestsMatch": "No requests match your current filters",
    "requests.submitted": "Submitted",
  },
  am: {
    // ─────────────────────────────────────────────────────────────
    // Common / General
    // ─────────────────────────────────────────────────────────────
    "app.title": "INSA CMBMS",
    "app.subtitle":
      "INSA CMBMS የፕሮጀክት ማረጋገጫ፣ የቦታ ቅድሚያ እና የጥገና ስርዓቶችን በሙሉ ግልጽነት እና ተጠያቂነት ያካትታል።",

    "app.tagline": "የመረጃ አውታረ መረብ ደህንነት ኤጀንሲ — ኢትዮጵያ",

    // ─────────────────────────────────────────────────────────────
    // Navigation
    // ─────────────────────────────────────────────────────────────
    "nav.dashboard": "ዳሽቦርድ",
    "nav.projects": "ካፒታል ፕሮጀክቶች",
    "nav.bookings": "ቦታና ቅድሚያ",
    "nav.maintenance": "ጥገና",
    "nav.notifications": "ማሳወቂያዎች",
    "nav.reports": "ሪፖርቶችና ትንታኔ",
    "nav.users": "የተጠቃሚ አስተዳደር",
    "nav.config": "የስርዓት ማዋቀር",
    "nav.allRequests": "ሁሉም የተጠቃሚ ጥያቄዎች",

    // ─────────────────────────────────────────────────────────────
    // Authentication
    // ─────────────────────────────────────────────────────────────
    "auth.login": "ግባ",
    "auth.logout": "ውጣ",
    "auth.register": "መዳረሻ ጠይቅ",
    "auth.welcomeBack": "እንኳን ደህና መጡ",
    "auth.securePortal": "ደህንነቱ የተጠበቀ የመዳረሻ በር",
    "auth.signInPrompt": "ለመቀጠል በእርስዎ ምስክርነት ይግቡ።",
    "auth.email": "ኢሜይል አድራሻ",
    "auth.password": "የይለፍ ቃል",
    "auth.forgotPassword": "የይለፍ ቃል ረስተዋል?",
    "auth.signingIn": "በመግባት ላይ...",
    "auth.demoQuickLogin": "ፈጣን የመግቢያ ማሳያ",
    "auth.noAccount": "መለያ የሎትም?",
    "auth.protectedBy": "በደህንነት ማዕቀፍ የተጠበቀ",
    "auth.loggedInAs": "ገብተዋል እንደ",

    // Roles
    "role.admin": "አስተዳዳሪ",
    "role.user": "ተጠቃሚ",
    "role.technician": "ቴክኒሺያን",

    // ─────────────────────────────────────────────────────────────
    // Module Labels
    // ─────────────────────────────────────────────────────────────
    "module.projects": "ካፒታል ፕሮጀክቶችና ንድፍ",
    "module.bookings": "የቦታ ምደባና ቅድሚያ",
    "module.maintenance": "አስቸኳይ ጥገናና HVAC",

    // ─────────────────────────────────────────────────────────────
    // Status
    // ─────────────────────────────────────────────────────────────
    "status.pending": "በመጠባበቅ",
    "status.approved": "ፀድቋል",
    "status.rejected": "ተቃውሟል",
    "status.completed": "ተጠናቋል",
    "status.inProgress": "በሂደት ላይ",
    "status.scheduled": "ተይዟል",
    "status.cancelled": "ተሰርዟል",
    "status.onHold": "በእገዳ ላይ",

    // ─────────────────────────────────────────────────────────────
    // Priority
    // ─────────────────────────────────────────────────────────────
    "priority.low": "ዝቅተኛ",
    "priority.medium": "መካከለኛ",
    "priority.high": "ከፍተኛ",
    "priority.urgent": "አስቸኳይ",
    "priority.critical": "ወሳኝ",

    // ─────────────────────────────────────────────────────────────
    // Common Actions
    // ─────────────────────────────────────────────────────────────
    "action.submit": "ላክ",
    "action.cancel": "ሰርዝ",
    "action.save": "አስቀምጥ",
    "action.delete": "ሰርዝ",
    "action.edit": "አርትዕ",
    "action.view": "እይ",
    "action.approve": "ፀድቅ",
    "action.reject": "ውድቅ አድርግ",
    "action.download": "አውርድ",
    "action.export": "ወደ ውጭ ላክ",
    "action.search": "ፈልግ",
    "action.filter": "አጣራ",
    "action.close": "ዝጋ",
    "action.back": "ተመለስ",
    "action.next": "ቀጣይ",
    "action.viewAll": "ሁሉንም እይ",
    "action.viewDetails": "ዝርዝር እይ",
    "action.collapse": "ሰብስብ",

    // ─────────────────────────────────────────────────────────────
    // Form Fields
    // ─────────────────────────────────────────────────────────────
    "form.title": "ርዕስ",
    "form.description": "መግለጫ",
    "form.location": "አካባቢ",
    "form.date": "ቀን",
    "form.startDate": "የመጀመሪያ ቀን",
    "form.endDate": "የመጨረሻ ቀን",
    "form.category": "ምድብ",
    "form.budget": "በጀት",
    "form.status": "ሁኔታ",
    "form.priority": "ቅድሚያ",
    "form.assignedTo": "ተመድቦ ለ",
    "form.createdBy": "የተፈጠረው በ",
    "form.notes": "ማስታወሻዎች",
    "form.attachments": "አባሪዎች",
    "form.comments": "አስተያየቶች",
    "form.type": "ዓይነት",
    "form.department": "ክፍል",
    "form.phone": "ስልክ",
    "form.contact": "ተገናኝ",

    // ─────────────────────────────────────────────────────────────
    // Dashboard
    // ─────────────────────────────────────────────────────────────
    "dashboard.welcome": "እንኳን ደህና መጡ",
    "dashboard.overview": "አጠቃላይ እይታ",
    "dashboard.statistics": "ስታቲስቲክስ",
    "dashboard.recentActivity": "የቅርብ ጊዜ እንቅስቃሴ",
    "dashboard.quickActions": "ፈጣን ድርጊቶች",
    "dashboard.myRequests": "የእኔ ጥያቄዎች",
    "dashboard.pendingApprovals": "በመጠባበቅ ላይ ያሉ ፍቃዶች",
    "dashboard.totalRequests": "ጠቅላላ ጥያቄዎች",
    "dashboard.activeProjects": "ንቁ ፕሮጀክቶች",
    "dashboard.openBookings": "ክፍት ቅድሚያዎች",
    "dashboard.urgentIssues": "አስቸኳይ ጉዳዮች",

    // ─────────────────────────────────────────────────────────────
    // Projects
    // ─────────────────────────────────────────────────────────────
    "projects.title": "ካፒታል ፕሮጀክቶች",
    "projects.newProject": "አዲስ ፕሮጀክት",
    "projects.projectTitle": "የፕሮጀክት ርዕስ",
    "projects.projectDescription": "የፕሮጀክት መግለጫ",
    "projects.estimatedCost": "የሚገመተው ዋጋ",
    "projects.fundingSource": "የገንዘብ ምንጭ",
    "projects.designRequirements": "የንድፍ መስፈርቶች",
    "projects.allProjects": "ሁሉም ፕሮጀክቶች",
    "projects.myProjects": "የእኔ ፕሮጀክቶች",
    "projects.viewProject": "ፕሮጀክት እይ",
    "projects.projectDetails": "የፕሮጀክት ዝርዝሮች",
    "projects.timeline": "የጊዜ መስመር",
    "projects.milestones": "ምዕራፎች",

    // ─────────────────────────────────────────────────────────────
    // Bookings
    // ─────────────────────────────────────────────────────────────
    "bookings.title": "ቦታና ቅድሚያ",
    "bookings.newBooking": "አዲስ ቅድሚያ",
    "bookings.spaceName": "የቦታ ስም",
    "bookings.purpose": "ዓላማ",
    "bookings.attendees": "የተሳታፊዎች ብዛት",
    "bookings.bookingDate": "የቅድሚያ ቀን",
    "bookings.timeSlot": "የጊዜ ክፍል",
    "bookings.allBookings": "ሁሉም ቅድሚያዎች",
    "bookings.myBookings": "የእኔ ቅድሚያዎች",
    "bookings.upcomingBookings": "የሚመጡ ቅድሚያዎች",
    "bookings.availableSpaces": "ያሉ ቦታዎች",

    // ─────────────────────────────────────────────────────────────
    // Maintenance
    // ─────────────────────────────────────────────────────────────
    "maintenance.title": "ጥገናና ጥገና",
    "maintenance.newRequest": "አዲስ የጥገና ጥያቄ",
    "maintenance.issueType": "የችግር ዓይነት",
    "maintenance.issueDescription": "የችግር መግለጫ",
    "maintenance.affectedArea": "የተጎዳው አካባቢ",
    "maintenance.urgencyLevel": "የአስቸኳይነት ደረጃ",
    "maintenance.allRequests": "ሁሉም ጥያቄዎች",
    "maintenance.myRequests": "የእኔ ጥያቄዎች",
    "maintenance.assignedToMe": "የተመደበኝ",
    "maintenance.requestDetails": "የጥያቄ ዝርዝሮች",

    // ─────────────────────────────────────────────────────────────
    // Notifications
    // ─────────────────────────────────────────────────────────────
    "notifications.title": "ማሳወቂያዎች",
    "notifications.unread": "ያልተነበበ",
    "notifications.markAllRead": "ሁሉንም እንደተነበበ አድርግ",
    "notifications.noNotifications": "ማሳወቂያዎች የሉም",
    "notifications.viewAll": "ሁሉንም ማሳወቂያዎች እይ →",

    // ─────────────────────────────────────────────────────────────
    // Reports
    // ─────────────────────────────────────────────────────────────
    "reports.title": "ሪፖርቶችና ትንታኔ",
    "reports.generate": "ሪፖርት አዘጋጅ",
    "reports.exportData": "መረጃ ወደ ውጭ ላክ",
    "reports.dateRange": "የቀን ክልል",
    "reports.reportType": "የሪፖርት ዓይነት",

    // ─────────────────────────────────────────────────────────────
    // Users
    // ─────────────────────────────────────────────────────────────
    "users.title": "የተጠቃሚ አስተዳደር",
    "users.addUser": "ተጠቃሚ ጨምር",
    "users.name": "ስም",
    "users.email": "ኢሜይል",
    "users.role": "ሚና",
    "users.department": "ክፍል",
    "users.status": "ሁኔታ",
    "users.active": "ንቁ",
    "users.inactive": "እንቅልፍ",

    // ─────────────────────────────────────────────────────────────
    // Messages & Placeholders
    // ─────────────────────────────────────────────────────────────
    "message.noData": "መረጃ የለም",
    "message.loading": "በመጫን ላይ...",
    "message.error": "ስህተት ተፈጥሯል",
    "message.success": "ክዋኔው በተሳካ ሁኔታ ተጠናቋል",
    "message.confirmDelete": "ይህን መሰረዝ እርግጠኛ ነዎት?",
    "placeholder.search": "ጥያቄዎችን፣ መለያዎችን ፈልግ...",
    "placeholder.selectDate": "ቀን ምረጥ",
    "placeholder.enterText": "ጽሑፍ አስገባ...",

    // ─────────────────────────────────────────────────────────────
    // Additional Dashboard
    // ─────────────────────────────────────────────────────────────
    "dashboard.systemHealth": "የስርዓት ጤንነት",
    "dashboard.kpiMetrics": "KPI መለኪያዎች",
    "dashboard.activityLog": "የእንቅስቃሴ ምዝግብ ማስታወሻ",
    "dashboard.viewDashboard": "ዳሽቦርድ እይ",
    "dashboard.noActivity": "የቅርብ ጊዜ እንቅስቃሴ የለም",
    "dashboard.averageCompletionTime": "አማካይ የማጠናቀቂያ ጊዜ",
    "dashboard.days": "ቀናት",

    // ─────────────────────────────────────────────────────────────
    // Admin Dashboard
    // ─────────────────────────────────────────────────────────────
    "admin.masterControl": "የአስተዳዳሪ ማስተር ተቆጣጣሪ ንብርብር",
    "admin.systemOverview": "የስርዓት አጠቃላይ እይታ",
    "admin.requestsAwaitingAction": "እርምጃ በመጠባበቅ ላይ ያሉ ጥያቄዎች",
    "admin.noRequestsAwaitingAction": "እርምጃ በመጠባበቅ ላይ ያሉ ጥያቄዎች የሉም",
    "admin.requestID": "የጥያቄ መለያ",
    "admin.submittedBy": "ያቀረበው",
    "admin.viewAllRequests": "ሁሉንም ጥያቄዎች እይ",
    "admin.allUserRequests": "ሁሉም የተጠቃሚ ጥያቄዎች",
    "admin.systemConfig": "የስርዓት ማዋቀር",
    "admin.across": "በውስጥ",
    "admin.modules": "ሞጁሎች",

    // ─────────────────────────────────────────────────────────────
    // Projects - Extended
    // ─────────────────────────────────────────────────────────────
    "projects.submitProject": "ፕሮጀክት አቅርብ",
    "projects.projectID": "የፕሮጀክት መለያ",
    "projects.submittedOn": "የቀረበበት",
    "projects.noProjects": "ፕሮጀክቶች አልተገኙም",
    "projects.filterByStatus": "በሁኔታ አጣራ",
    "projects.allStatuses": "ሁሉም ሁኔታዎች",
    "projects.requestDetails": "የጥያቄ ዝርዝሮች",
    "projects.budgetInfo": "የበጀት መረጃ",
    "projects.attachedDocuments": "የተያያዙ ሰነዶች",
    "projects.noDocuments": "ምንም የተያያዙ ሰነዶች የሉም",
    "projects.adminActions": "የአስተዳዳሪ ድርጊቶች",
    "projects.approveProject": "ፕሮጀክት ፀድቅ",
    "projects.rejectProject": "ፕሮጀክት ውድቅ አድርግ",
    "projects.statusHistory": "የሁኔታ ታሪክ",
    "projects.addNote": "ማስታወሻ ጨምር",
    "projects.internalNotes": "ውስጣዊ ማስታወሻዎች",
    "projects.noNotes": "ገና ማስታወሻዎች የሉም",
    "projects.projectApproved": "ፕሮጀክት በተሳካ ሁኔታ ፀድቋል",
    "projects.projectRejected": "ፕሮጀክት ውድቅ ተደርጓል",
    "projects.estimatedBudget": "የሚገመተው በጀት",
    "projects.actualCost": "ትክክለኛው ወጪ",
    "projects.costVariance": "የወጪ ልዩነት",
    "projects.enterProjectDetails": "የፕሮጀክት ዝርዝሮችን ከዚህ በታች ያስገቡ",
    "projects.enterTitle": "የፕሮጀክት ርዕስ ያስገቡ",
    "projects.enterDescription": "ዝርዝር የፕሮጀክት መግለጫ ያስገቡ",
    "projects.enterLocation": "የፕሮጀክት አካባቢ ያስገቡ",
    "projects.enterEstimatedCost": "የሚገመተው ወጪ በብር ያስገቡ",
    "projects.enterFundingSource": "የገንዘብ ምንጭ ያስገቡ",
    "projects.enterDesignRequirements": "የንድፍ መስፈርቶችን ይግለጹ",
    "projects.reviewAndSubmit": "ይገምግሙና ያቅርቡ",

    // ─────────────────────────────────────────────────────────────
    // Bookings - Extended
    // ─────────────────────────────────────────────────────────────
    "bookings.submitBooking": "ቅድሚያ አቅርብ",
    "bookings.bookingID": "የቅድሚያ መለያ",
    "bookings.bookedOn": "የተያዘበት",
    "bookings.noBookings": "ቅድሚያዎች አልተገኙም",
    "bookings.requestedBy": "የጠየቀው",
    "bookings.bookingDetails": "የቅድሚያ ዝርዝሮች",
    "bookings.approveBooking": "ቅድሚያ ፀድቅ",
    "bookings.rejectBooking": "ቅድሚያ ውድቅ አድርግ",
    "bookings.bookingApproved": "ቅድሚያ በተሳካ ሁኔታ ፀድቋል",
    "bookings.bookingRejected": "ቅድሚያ ውድቅ ተደርጓል",
    "bookings.enterBookingDetails": "የቅድሚያ ዝርዝሮችን ከዚህ በታች ያስገቡ",
    "bookings.enterSpaceName": "የቦታ ስም ያስገቡ",
    "bookings.enterPurpose": "የቅድሚያ ዓላማ ያስገቡ",
    "bookings.enterAttendees": "የተሳታፊዎች ብዛት ያስገቡ",
    "bookings.selectBookingDate": "የቅድሚያ ቀን ይምረጡ",
    "bookings.selectTimeSlot": "የጊዜ ክፍል ይምረጡ",
    "bookings.morningSlot": "ጠዋት (8:00 ጠዋት - 12:00 ከሰዓት)",
    "bookings.afternoonSlot": "ከሰዓት በኋላ (1:00 ከሰዓት - 5:00 ከሰዓት)",
    "bookings.eveningSlot": "ምሽት (5:00 ከሰዓት - 9:00 ምሽት)",
    "bookings.fullDaySlot": "ሙሉ ቀን (8:00 ጠዋት - 5:00 ከሰዓት)",
    "bookings.spaceType": "የቦታ ዓይነት",
    "bookings.conferenceRoom": "የስብሰባ ክፍል",
    "bookings.trainingHall": "የስልጠና አዳራሽ",
    "bookings.laboratory": "ላብራቶሪ",
    "bookings.office": "ቢሮ",
    "bookings.otherSpace": "ሌላ",

    // ─────────────────────────────────────────────────────────────
    // Maintenance - Extended
    // ─────────────────────────────────────────────────────────────
    "maintenance.submitRequest": "ጥያቄ አቅርብ",
    "maintenance.requestID": "የጥያቄ መለያ",
    "maintenance.reportedOn": "የተዘገበበት",
    "maintenance.noRequests": "የጥገና ጥያቄዎች አልተገኙም",
    "maintenance.reportedBy": "ዘግቧል",
    "maintenance.assignTechnician": "ቴክኒሺያን ምደባ",
    "maintenance.selectTechnician": "ቴክኒሺያን ይምረጡ",
    "maintenance.updateStatus": "ሁኔታን አዘምን",
    "maintenance.markRepaired": "እንደተጠገነ አድርግ",
    "maintenance.markCompleted": "እንደተጠናቀቀ አድርግ",
    "maintenance.statusUpdated": "ሁኔታ በተሳካ ሁኔታ ተዘምኗል",
    "maintenance.technicianAssigned": "ቴክኒሺያን በተሳካ ሁኔታ ተመድቧል",
    "maintenance.workLog": "የስራ ምዝግብ ማስታወሻ",
    "maintenance.addWorkNote": "የስራ ማስታወሻ ጨምር",
    "maintenance.enterWorkNote": "የስራ ማስታወሻ ያስገቡ",
    "maintenance.noWorkLogs": "ገና የስራ ምዝግብ ማስታወሻዎች የሉም",
    "maintenance.enterMaintenanceDetails": "የጥገና ጥያቄ ዝርዝሮችን ከዚህ በታች ያስገቡ",
    "maintenance.selectIssueType": "የችግር ዓይነት ይምረጡ",
    "maintenance.hvacIssue": "HVAC",
    "maintenance.electricalIssue": "ኤሌክትሪክ",
    "maintenance.plumbingIssue": "የውሃ ቧንቧ",
    "maintenance.structuralIssue": "አወቃቀራዊ",
    "maintenance.generalIssue": "አጠቃላይ ጥገና",
    "maintenance.enterIssueDescription": "ችግሩን በዝርዝር ይግለጹ",
    "maintenance.enterAffectedArea": "የተጎዳውን አካባቢ/ቦታ ይግለጹ",
    "maintenance.selectUrgency": "የአስቸኳይነት ደረጃ ይምረጡ",
    "maintenance.assignedTechnician": "የተመደበ ቴክኒሺያን",
    "maintenance.unassigned": "ያልተመደበ",
    "maintenance.estimatedTime": "የሚገመተው ጊዜ",
    "maintenance.repairCost": "የጥገና ወጪ",

    // ─────────────────────────────────────────────────────────────
    // Notifications - Extended
    // ─────────────────────────────────────────────────────────────
    "notifications.allNotifications": "ሁሉም ማሳወቂያዎች",
    "notifications.readNotifications": "የተነበቡ ማሳወቂያዎች",
    "notifications.unreadNotifications": "ያልተነበቡ ማሳወቂያዎች",
    "notifications.clearAll": "ሁሉንም አጽዳ",
    "notifications.noUnreadNotifications": "ያልተነበቡ ማሳወቂያዎች የሉም",
    "notifications.today": "ዛሬ",
    "notifications.yesterday": "ትናንት",
    "notifications.thisWeek": "በዚህ ሳምንት",
    "notifications.older": "የቆዩ",

    // ─────────────────────────────────────────────────────────────
    // Reports - Extended
    // ─────────────────────────────────────────────────────────────
    "reports.systemReports": "የስርዓት ሪፖርቶችና ትንታኔ",
    "reports.projectsReport": "የፕሮጀክቶች ሪፖርት",
    "reports.bookingsReport": "የቅድሚያዎች ሪፖርት",
    "reports.maintenanceReport": "የጥገና ሪፖርት",
    "reports.usersReport": "የተጠቃሚዎች ሪፖርት",
    "reports.exportPDF": "PDF አውርድ",
    "reports.exportExcel": "Excel አውርድ",
    "reports.exportCSV": "CSV አውርድ",
    "reports.selectReportType": "የሪፖርት ዓይነት ይምረጡ",
    "reports.selectDateRange": "የቀን ክልል ይምረጡ",
    "reports.from": "ከ",
    "reports.to": "እስከ",
    "reports.last7Days": "ባለፉት 7 ቀናት",
    "reports.last30Days": "ባለፉት 30 ቀናት",
    "reports.last90Days": "ባለፉት 90 ቀናት",
    "reports.customRange": "ብጁ ክልል",
    "reports.totalProjects": "ጠቅላላ ፕሮጀክቶች",
    "reports.totalBookings": "ጠቅላላ ቅድሚያዎች",
    "reports.totalMaintenanceRequests": "ጠቅላላ የጥገና ጥያቄዎች",
    "reports.completionRate": "የማጠናቀቂያ መጠን",
    "reports.averageResolutionTime": "አማካይ የመፍትሄ ጊዜ",
    "reports.projectsByStatus": "ፕሮጀክቶች በሁኔታ",
    "reports.bookingsByStatus": "ቅድሚያዎች በሁኔታ",
    "reports.maintenanceByPriority": "ጥገና በቅድሚያ",
    "reports.trendAnalysis": "አዝማሚያ ትንታኔ",
    "reports.performanceMetrics": "የአፈጻጸም መለኪያዎች",

    // ─────────────────────────────────────────────────────────────
    // Users Management - Extended
    // ─────────────────────────────────────────────────────────────
    "users.allUsers": "ሁሉም ተጠቃሚዎች",
    "users.addNewUser": "አዲስ ተጠቃሚ ጨምር",
    "users.editUser": "ተጠቃሚ አርትዕ",
    "users.deleteUser": "ተጠቃሚ ሰርዝ",
    "users.userDetails": "የተጠቃሚ ዝርዝሮች",
    "users.fullName": "ሙሉ ስም",
    "users.emailAddress": "ኢሜይል አድራሻ",
    "users.phoneNumber": "ስልክ ቁጥር",
    "users.userRole": "የተጠቃሚ ሚና",
    "users.selectRole": "ሚና ይምረጡ",
    "users.selectDepartment": "ክፍል ይምረጡ",
    "users.accountStatus": "የመለያ ሁኔታ",
    "users.activateUser": "ተጠቃሚን አንቃ",
    "users.deactivateUser": "ተጠቃሚን አሰናክል",
    "users.resetPassword": "የይለፍ ቃል እንደገና አስጀምር",
    "users.lastLogin": "የመጨረሻ መግባት",
    "users.createdOn": "የተፈጠረበት",
    "users.noUsers": "ተጠቃሚዎች አልተገኙም",
    "users.searchUsers": "ተጠቃሚዎችን ፈልግ",
    "users.filterByRole": "በሚና አጣራ",
    "users.filterByStatus": "በሁኔታ አጣራ",
    "users.userCreated": "ተጠቃሚ በተሳካ ሁኔታ ተፈጥሯል",
    "users.userUpdated": "ተጠቃሚ በተሳካ ሁኔታ ተዘምኗል",
    "users.userDeleted": "ተጠቃሚ በተሳካ ሁኔታ ተሰርዟል",
    "users.confirmDeleteUser": "ይህን ተጠቃሚ መሰረዝ እርግጠኛ ነዎት?",

    // ─────────────────────────────────────────────────────────────
    // System Config - Extended
    // ─────────────────────────────────────────────────────────────
    "config.title": "የስርዓት ማዋቀር",
    "config.generalSettings": "አጠቃላይ ቅንብሮች",
    "config.emailSettings": "የኢሜይል ቅንብሮች",
    "config.notificationSettings": "የማሳወቂያ ቅንብሮች",
    "config.slaSettings": "SLA ቅንብሮች",
    "config.workflowSettings": "የስራ ፍሰት ቅንብሮች",
    "config.systemName": "የስርዓት ስም",
    "config.timezone": "የጊዜ ሰቅ",
    "config.language": "ነባሪ ቋንቋ",
    "config.dateFormat": "የቀን ቅርጸት",
    "config.saveSettings": "ቅንብሮችን አስቀምጥ",
    "config.settingsSaved": "ቅንብሮች በተሳካ ሁኔታ ተቀምጠዋል",
    "config.emailNotifications": "የኢሜይል ማሳወቂያዎች",
    "config.smsNotifications": "የSMS ማሳወቂያዎች",
    "config.pushNotifications": "የግፊት ማሳወቂያዎች",
    "config.enableNotifications": "ማሳወቂያዎችን አንቃ",
    "config.disableNotifications": "ማሳወቂያዎችን አሰናክል",

    // ─────────────────────────────────────────────────────────────
    // Auth - Extended
    // ─────────────────────────────────────────────────────────────
    "auth.createAccount": "መለያ ፍጠር",
    "auth.haveAccount": "ቀድሞውኑ መለያ አለዎት?",
    "auth.signIn": "ግባ",
    "auth.fullName": "ሙሉ ስም",
    "auth.confirmPassword": "የይለፍ ቃል አረጋግጥ",
    "auth.agreeToTerms": "ውሎችና ሁኔታዎችን ተቀብያለሁ",
    "auth.resetPassword": "የይለፍ ቃል እንደገና አስጀምር",
    "auth.backToLogin": "ወደ መግቢያ ተመለስ",
    "auth.sendResetLink": "የዳግም ማስጀመሪያ አገናኝ ላክ",
    "auth.resetLinkSent": "የዳግም ማስጀመሪያ አገናኝ ወደ ኢሜልዎ ተልኳል",
    "auth.enterEmailForReset":
      "የይለፍ ቃል ዳግም ማስጀመሪያ አገናኝ ለመቀበል የኢሜይል አድራሻዎን ያስገቡ",
    "auth.registrationRequest": "የምዝገባ ጥያቄ",
    "auth.requestAccessDesc": "ወደ INSA CMBMS ስርዓት መዳረሻ ጠይቅ",
    "auth.department": "ክፍል",
    "auth.position": "የስራ ቦታ",
    "auth.reason": "የመዳረሻ ምክንያት",
    "auth.submitRequest": "ጥያቄ አቅርብ",
    "auth.requestSubmitted": "ጥያቄ በተሳካ ሁኔታ ቀርቧል",

    // ─────────────────────────────────────────────────────────────
    // Common UI Elements
    // ─────────────────────────────────────────────────────────────
    "common.showing": "በማሳየት ላይ",
    "common.of": "ከ",
    "common.results": "ውጤቶች",
    "common.page": "ገጽ",
    "common.previous": "ቀዳሚ",
    "common.next": "ቀጣይ",
    "common.rowsPerPage": "ረድፎች በገጽ",
    "common.selectAll": "ሁሉንም ምረጥ",
    "common.deselectAll": "ሁሉንም አትምረጥ",
    "common.selected": "ተመርጧል",
    "common.bulkActions": "የጅምላ ድርጊቶች",
    "common.refresh": "አድስ",
    "common.print": "አትም",
    "common.share": "አጋራ",
    "common.copy": "ቅዳ",
    "common.copied": "ተቀድቷል!",
    "common.copyToClipboard": "ወደ ቅንጥብ ሰሌዳ ቅዳ",
    "common.yes": "አዎ",
    "common.no": "አይ",
    "common.confirm": "አረጋግጥ",
    "common.required": "ያስፈልጋል",
    "common.optional": "አማራጭ",
    "common.all": "ሁሉም",
    "common.none": "ምንም",
    "common.or": "ወይም",
    "common.and": "እና",

    // Greetings
    "greeting.morning": "ደህና ጠዋት",
    "greeting.afternoon": "ደህና ቀን",
    "greeting.evening": "ደህና ምሽት",

    // Dashboard - Extended
    "dashboard.trackRequests": "ጥያቄዎችዎን፣ ቅድሚያዎች እና ጥገናዎን ይከታተሉ",
    "dashboard.assignedTasksQueue": "የተመደቡ ስራዎቾ እና የጥገና ወረፋ",
    "dashboard.myProjects": "የእኔ ፕሮጀክቶች",
    "dashboard.myBookings": "የእኔ ቅድሚያዎች",
    "dashboard.myMaintenance": "የእኔ ጥገና",
    "dashboard.unreadAlerts": "ያልተነበቡ ማሳወቂያዎች",
    "dashboard.assignedTasks": "የተመደቡ ስራዎች",
    "dashboard.activeRepairs": "ንቁ ጥገናዎች",
    "dashboard.completedTasks": "ተጠናቋል",
    "dashboard.currentlyWorking": "አሁን በስራ ላይ",
    "dashboard.totalAssigned": "ጠቅላላ ተመድቧል",
    "dashboard.thisMonth": "በዚህ ወር",
    "dashboard.unreadAlertsNotif": "ያልተነበቡ ማሳወቂያዎች",
    "dashboard.notifications": "ማሳወቂያዎች",
    "dashboard.inProgress": "በሂደት ላይ",
    "dashboard.confirmed": "ተፈቅዷል",
    "dashboard.resolved": "ተፈቷል",
    "dashboard.submitProjectRequest": "የፕሮጀክት ጥያቄ አቅርብ",
    "dashboard.bookASpace": "ቦታ ያዝ",
    "dashboard.reportMaintenance": "ጥገና ዘግብ",
    "dashboard.criticalAlerts": "ወሳኝ ማሳወቂያዎች",
    "dashboard.noCriticalAlerts": "ምንም ወሳኝ ማሳወቂያዎች የሉም",
    "dashboard.upcomingBookings": "የሚመጡ ቅድሚያዎች",
    "dashboard.attendees": "ተሳታፊዎች",

    // Projects - Page Specific
    "projects.streamA": "ዥረት A",
    "projects.projectsFound": "ፕሮጀክት(ዎች) ተገኝቷል",
    "projects.newProjectRequest": "አዲስ የፕሮጀክት ጥያቄ",
    "projects.searchByTitleOrID": "በርዕስ ወይም ምልክት ፈልግ...",
    "projects.classification": "ምደባ",
    "projects.budgetETB": "በጀት (ብር)",
    "projects.updated": "ተዘምኗል",
    "projects.actions": "ድርጊቶች",
    "projects.noProjectsFound": "ፕሮጀክቶች አልተገኙም",
    "projects.tryAdjusting": "ፍለጋዎን ወይም ማጣሪያዎን ያስተካክሉ",
    "projects.submitFirstRequest": "የመጀመሪያ ጥያቄ አቅርብ",
    "projects.review": "ግምግሙ",
    "projects.workflowProgress": "የስራ ፍሰት ሂደት",
    "projects.projectNotFound": "ፕሮጀክት አልተገኘም",
    "projects.backToProjects": "← ወደ ፕሮጀክቶች ተመለስ",
    "projects.description": "የፕሮጀክት መግለጫ",
    "projects.notYetAssigned": "ገና አልተሰጠም",
    "projects.activityTimeline": "የእንቅስቃሴ ጊዜ ሰሌዳ",
    "projects.documents": "ሰነዶች",
    "projects.noDocumentsAttached": "ምንም ሰነዶች ያልተያያዙ",
    "projects.download": "አውርድ",
    "projects.startReview": "ግምግምት ጀምር",
    "projects.markInProgress": "እንደሚሠራ ምልክት አድርግ",
    "projects.markCompleted": "እንደተጠናቀቀ ምልክት አድርግ",
    "projects.assignProfessional": "ባለሙያ ሰጥ",
    "projects.selectStaff": "ሰራተኛ ምረጥ...",
    "projects.sendToRequester": "ለጠያቂው ላክ",
    "projects.quickInfo": "ፈጣን መረጃ",
    "projects.created": "ተፈጥሯል",
    "projects.lastUpdated": "ላቅ ዘምኗል",
    "projects.filesCount": "ፋይል(ዎች)",
    "projects.timelineEventsCount": "የጊዜ ሰሌዳ ክስተቶች",
    "projects.actionApplied": "ድርጊቱ ተፈጻሚ ሆኗል",
    "projects.addCommentOrReason": "አስተያየት ወይም ምክንያት ያስገቡ...",

    // Bookings - Page Specific
    "bookings.spaceAllocation": "የቦታ ምደባና ቅድሚያ",
    "bookings.bookingsCount": "ቅድሚያ(ዎች)",
    "bookings.list": "ዝርዝር",
    "bookings.calendar": "የቀን መቆጠሪያ",
    "bookings.spaces": "ቦታዎች",
    "bookings.addSpace": "ቦታ ጨምር",
    "bookings.searchBookings": "ቅድሚያዎችን ፈልግ...",
    "bookings.noBookingsFound": "ቅድሚያዎች አልተገኙም",
    "bookings.noBookingsMatch": "ምንም ቅድሚያዎች ማጣሪያዎን አያሟሉም",
    "bookings.requirements": "መስፈርቶች",
    "bookings.totalSpaces": "ጠቅላላ ቦታዎች",
    "bookings.availableSpacesCount": "ያሉ",
    "bookings.occupiedSpaces": "የተያዙ",
    "bookings.searchSpaces": "ቦታዎችን ፈልግ...",
    "bookings.allTypes": "ሁሉም ዓይነቶች",
    "bookings.editSpace": "ቦታ አርትዕ",
    "bookings.addNewSpace": "አዲስ ቦታ ጨምር",
    "bookings.spaceName_label": "የቦታ ስም *",
    "bookings.spaceType_label": "የቦታ ዓይነት *",
    "bookings.capacity_label": "አቅም *",
    "bookings.floorLocation": "ፎቅ / አካባቢ *",
    "bookings.availabilityStatus": "የተገኝነት ሁኔታ",
    "bookings.available_btn": "ያለ",
    "bookings.occupied_btn": "የተያዘ",
    "bookings.saveChanges": "ለውጦችን አስቀምጥ",
    "bookings.deleteSpace": "ቦታ ይሰረዝ?",
    "bookings.deleteSpaceWarning": "ይህ ድርጊት ሊቀለበስ አይችልም። ቅድሚያዎች ሊጎዱ ይችላሉ።",
    "bookings.yesDelete": "አዎ፣ ሰርዝ",
    "bookings.noBookingType": "አዲስ ጥያቄ",
    "bookings.officeSpaceAllocation": "የቢሮ ቦታ ምደባ",
    "bookings.sharedHallBooking": "የጋራ አዳራሽ / ክፍል ቅድሚያ",
    "bookings.selectRequestType": "የጥያቄ ዓይነት ምረጥ",
    "bookings.reviewAndConfirm": "ያረጋግጡ",
    "bookings.allocationSubmitted": "የምደባ ጥያቄ ቀርቧል!",
    "bookings.bookingSubmitted": "ቅድሚያ ቀርቧል!",
    "bookings.viewBookings": "ቅድሚያዎችን እይ",

    // Maintenance - Page Specific
    "maintenance.urgentRepairsHVAC": "አስቸኳይ ጥገናና HVAC",
    "maintenance.maintenanceAndRepairs": "ጥገናና ጥገናዎች",
    "maintenance.ticketsCount": "ቲኬት(ዎች)",
    "maintenance.kanban": "ካንባን",
    "maintenance.list": "ዝርዝር",
    "maintenance.newRequest_btn": "አዲስ ጥያቄ",
    "maintenance.noTickets": "ቲኬቶች የሉም",
    "maintenance.noTicketsFound": "ቲኬቶች አልተገኙም",
    "maintenance.noTicketsMatch": "ምንም የጥገና ቲኬቶች ማጣሪያዎን አያሟሉም",
    "maintenance.assignTech": "+ ቴክኒሺያን ምደባ",
    "maintenance.assignTechBtn": "ቴክ ምደባ",
    "maintenance.selectTechOption": "ቴክ ምረጥ...",
    "maintenance.viewDetails": "ዝርዝሮችን እይ",
    "maintenance.submitMaintenanceRequest": "የጥገና ጥያቄ አቅርብ",
    "maintenance.selectMaintenanceClassification": "የጥገና ምደባ ምረጥ",
    "maintenance.urgentRepairsClass": "አስቸኳይ ጥገናዎች",
    "maintenance.hvacMaintenance": "HVAC እና AC ጥገና",
    "maintenance.issueTitle": "የችግር ርዕስ *",
    "maintenance.repairType": "የጥገና ዓይነት",
    "maintenance.hvacServiceType": "የ HVAC አገልግሎት ዓይነት",
    "maintenance.priorityLevel": "የቅድሚያ ደረጃ",
    "maintenance.problemDescription": "የችግር መግለጫ *",
    "maintenance.suspectedParts": "የሚያስፈልጉ ተጠርጣሪ ክፍሎች",
    "maintenance.costEstimation": "የወጪ ግምት (አማራጭ)",
    "maintenance.locationContact": "አካባቢና ተገናኝ ዝርዝሮች",
    "maintenance.buildingBlock": "ህንጻ / ብሎክ *",
    "maintenance.floor_field": "ፎቅ *",
    "maintenance.roomOfficeNo": "ክፍል / ቢሮ ቁጥር",
    "maintenance.contactPerson": "ተገናኝ ሰው",
    "maintenance.contactPhone": "ተገናኝ ስልክ *",
    "maintenance.additionalNotes": "ተጨማሪ ማስታወሻዎች",
    "maintenance.attachPhotos": "ፎቶ / ሰነዶች ያያይዙ",
    "maintenance.dragDropPhotos": "ፎቶዎችን ወደዚህ ጎትቶ ጣሉ",
    "maintenance.reviewAndSubmit": "ይገምግሙና ያቅርቡ",
    "maintenance.requestSubmitted_title": "ጥያቄ ቀርቧል!",
    "maintenance.autoAssignedTo": "ወደዚህ ተልኳል:",
    "maintenance.viewMaintenance": "ጥገናዎችን እይ",
    "maintenance.goToDashboard": "ወደ ዳሽቦርድ ሂድ",
    "maintenance.maintenanceWorkflow": "የጥገና ስራ ፍሰት",
    "maintenance.ticketDetails": "የቲኬት ዝርዝሮች",
    "maintenance.location_label": "አካባቢ",
    "maintenance.floor_label": "ፎቅ",
    "maintenance.reportedBy_label": "ዘግቧል",
    "maintenance.assignedTo_label": "ተሰጥቷል",
    "maintenance.notAssigned": "ያልተሰጠ",
    "maintenance.created_label": "ተፈጥሯል",
    "maintenance.resolved_label": "ተፈቷል",
    "maintenance.pending_label": "በመጠባበቅ",
    "maintenance.attachments_label": "አባሪዎች",
    "maintenance.noAttachments": "አባሪዎች የሉም",
    "maintenance.uploadRepairProof": "የጥገና ማረጋገጫ / ማጠናቀቂያ ፎቶ ስቀል",
    "maintenance.repairCostTracking": "የጥገና ወጪ ክትትል",
    "maintenance.materialsCost": "የቁሳቁስ ወጪ (ብር)",
    "maintenance.laborCostETB": "የሰው ሃይል ወጪ (ብር)",
    "maintenance.partsUsed": "ያገለገሉ ክፍሎች / ቁሳቁሶች",
    "maintenance.totalRepairCost": "ጠቅላላ የጥገና ወጪ",
    "maintenance.saveCostData": "የወጪ መረጃ አስቀምጥ",
    "maintenance.activityTimeline": "የእንቅስቃሴ ጊዜ ሰሌዳ",
    "maintenance.adminActions_label": "የአስተዳዳሪ ድርጊቶች",
    "maintenance.assignAndNotify": "ምደባ እና ማሳወቅ",
    "maintenance.verifyAndClose": "ያረጋግጡ እና ቲኬቱን ዝጉ",
    "maintenance.saveNote": "ማስታወሻ አስቀምጥ",
    "maintenance.technicianNote": "የቴክኒሺያን ማስታወሻ",
    "maintenance.startRepair": "ጥገና ጀምር",
    "maintenance.markAsRepaired": "እንደተጠገነ ምልክት አድርግ",
    "maintenance.confirmCompletion": "ማጠናቀቅ አረጋግጥ",
    "maintenance.confirmIssueResolved": "✓ ችግሩ መፈታቱን አረጋግጥ",
    "maintenance.ticketVerifyDesc":
      "ቴክኒሺያኑ ይህ ችግር እንደተጠገነ ምልክት አድርጓል። እባክዎ ያረጋግጡ።",
    "maintenance.ticketInfo": "የቲኬት መረጃ",
    "maintenance.ticketID": "የቲኬት መለያ",
    "maintenance.timelineEvents_label": "የጊዜ ሰሌዳ ክስተቶች",
    "maintenance.attachmentsCount": "አባሪዎች",
    "maintenance.totalCost": "ጠቅላላ ወጪ",
    "maintenance.ticketNotFound": "ቲኬት አልተገኘም",
    "maintenance.costDataSaved": "የወጪ መረጃ በተሳካ ሁኔታ ተቀምጧል",

    // Notifications - Page Specific
    "notifications.allCaughtUp": "ሁሉም ቅደምተከተሉ ተጠናቋል!",
    "notifications.allFilter": "ሁሉም",
    "notifications.unreadFilter": "ያልተነበቡ",
    "notifications.readFilter": "የተነበቡ",
    "notifications.markRead": "እንደተነበበ ምልክት አድርግ",
    "notifications.noUnreadFound": "ያልተነበቡ ማሳወቂያዎች የሉም",
    "notifications.noNotificationsFound": "ማሳወቂያዎች አልተገኙም",
    "notifications.youreAllCaughtUp": "ሁሉም ቅደምተከተሉ ተጠናቋል!",
    "notifications.total": "ጠቅላላ",
    "notifications.read": "የተነበቡ",

    // Reports - Page Specific
    "reports.reportsAndAnalytics": "ሪፖርቶችና ትንታኔ",
    "reports.systemWidePerformance":
      "የስርዓት አፈጻጸም መለኪያዎች፣ የወጪ ክትትል እና የጥገና ትንታኔ",
    "reports.totalProjects_label": "ጠቅላላ ፕሮጀክቶች",
    "reports.avgMTTR": "አማካይ MTTR (ሰዓ)",
    "reports.totalBudgetETB": "ጠቅላላ በጀት (ብር)",
    "reports.confirmedBookings_label": "የተፈቀዱ ቅድሚያዎች",
    "reports.preventiveMaintSchedules": "የቅድሚያ ጥገና መርሃ ግብሮች ጊዜ አልፏቸዋል",
    "reports.reviewAndDispatch": "ከዚህ በታች ያለውን ይገምግሙ እና ቴክኒሺያኖችን ወዲያው ላኩ።",
    "reports.requestVolumeOverTime": "የጥያቄ ብዛት በጊዜ ሂደት",
    "reports.monthlyBreakdown": "ወርሃዊ ትንታኔ በሞጁል",
    "reports.requestStatusDist": "የጥያቄ ሁኔታ ስርጭት",
    "reports.overallCompletionRates": "አጠቃላይ ደረጃዎች",
    "reports.meanTimeToRepair": "አማካይ የጥገና ጊዜ (MTTR)",
    "reports.avgHoursToResolve": "አማካይ ሰዓቶች ለጥገና ቲኬቶች ፍቱ",
    "reports.spaceUtilizationRate": "የቦታ አጠቃቀም ደረጃ",
    "reports.bookingFrequency": "የቅድሚያ ድግግሞሽ (%)",
    "reports.budgetVsActual": "በጀት vs ትክክለኛ ወጪ ክትትል (ብር)",
    "reports.plannedVsActual": "ታቅዶ vs ትክ. ወጪ",
    "reports.repairCostPerTicket": "የጥገና ወጪ በቲኬት (ብር)",
    "reports.materialsLaborBreakdown": "ቁሳቁሶች + ሰው ሃይል ትንታኔ",
    "reports.teamPerformance": "የጥገና ቡድን አፈጻጸም",
    "reports.multiDimensional": "ብዙ-ልኬታዊ ራዳር",
    "reports.technicianKPIs": "የቴክኒሺያን KPIዎች",
    "reports.individualPerformance": "ግለሰባዊ ማጠቃለያ",
    "reports.completionRate_label": "የማጠናቀቂያ ደረጃ",
    "reports.preventiveMaintenanceSched": "የቅድሚያ ጥገና መርሃ ግብር",
    "reports.recurringSystemMaint": "ተደጋጋሚ የስርዓት ጥገና",
    "reports.performanceSummary": "የአፈጻጸም ማጠቃለያ",
    "reports.system_equipment": "ስርዓት / መሳሪያ",
    "reports.frequency": "ድግግሞሽ",
    "reports.lastDone": "ያለፈው ጥገና",
    "reports.nextDue": "ቀጣይ ጊዜ",
    "reports.assignee": "ተሰጥቷቸዋል",
    "reports.metric": "መለኪያ",
    "reports.capitalProjects": "ካፒታል ፕሮጀክቶች",
    "reports.spaceAndBooking": "ቦታና ቅድሚያ",
    "reports.maintenance_col": "ጥገና",
    "reports.total_col": "ጠቅላላ",
    "reports.totalRequests_row": "ጠቅላላ ጥያቄዎች",
    "reports.completedConfirmed": "ተጠናቋል / ተፈቅዷል",
    "reports.pendingOpen": "ተሰጥቷል / ክፍት",
    "reports.rejectedCancelled": "ውድቅ / ተዘግቷል",
    "reports.satisfaction": "እርካታ",
    "reports.assigned": "ተሰጥቷል",
    "reports.completed": "ተጠናቋል",

    // Users - Page Specific
    "users.usersCount": "ተጠቃሚ(ዎች)",
    "users.active_count": "ንቁ",
    "users.administrators": "አስተዳዳሪዎች",
    "users.standardUsers": "መደበኛ ተጠቃሚዎች",
    "users.technicians": "ቴክኒሺያኖች",
    "users.user_col": "ተጠቃሚ",
    "users.id_col": "መለያ",
    "users.department_col": "ክፍል",
    "users.role_col": "ሚና",
    "users.status_col": "ሁኔታ",
    "users.joined_col": "ተቀላቀለ",
    "users.actions_col": "ድርጊቶች",
    "users.edit_btn": "አርትዕ",
    "users.disable_btn": "አሰናክል",
    "users.enable_btn": "አንቃ",
    "users.createNewUser": "አዲስ ተጠቃሚ ፍጠር",
    "users.allRoles": "ሁሉም ሚናዎች",
    "users.allStatuses": "ሁሉም ሁኔታዎች",
    "users.searchByNameEmailID": "በስም፣ ኢሜይል ወይም መለያ ፈልግ...",
    "users.phone_label": "ስልክ",
    "users.department_label": "ክፍል",
    "users.role_label": "ሚና *",
    "users.status_label": "ሁኔታ",
    "users.saveChanges_btn": "ለውጦችን አስቀምጥ",
    "users.createUser_btn": "ተጠቃሚ ፍጠር",
    "users.showing": "በማሳየት ላይ",
    "users.of": "ከ",
    "users.users": "ተጠቃሚዎች",

    // Admin Dashboard - Extended
    "admin.masterControlLayer": "ማስተር ቁጥጥር ንብርብር",
    "admin.systemAdministrator": "የስርዓት አስተዳዳሪ",
    "admin.criticalAlert": "ወሳኝ ማሳወቂያ",
    "admin.criticalAlerts_multi": "ወሳኝ ማሳወቂያዎች",
    "admin.pendingActions": "በሂደት ላይ ያሉ ድርጊቶች",
    "admin.overview": "አጠቃላይ እይታ",
    "admin.analytics": "ትንታኔ",
    "admin.workflow": "ስራ ፍሰት",
    "admin.activeUsers": "ንቁ ተጠቃሚዎች",
    "admin.pendingReviews": "በሂደት ላይ ያሉ ግምገማዎች",
    "admin.projectsAwaitingAction": "እርምጃ የሚጠብቁ ፕሮጀክቶች",
    "admin.spaceRequests": "የቦታ ጥያቄዎች",
    "admin.pendingApproval": "ፍቃድ በመጠባበቅ",
    "admin.openTickets": "ክፍት ቲኬቶች",
    "admin.slaCompliance": "SLA ተኳሃኝነት",
    "admin.ticketsResolvedOnTime": "ቲኬቶች በጊዜ ተፈተዋል",
    "admin.totalBudget": "ጠቅላላ በጀት",
    "admin.etbAcrossProjects": "ብር በሁሉም ፕሮጀክቶች",
    "admin.adminControlPanel": "የአስተዳዳሪ መቆጣጠሪያ ፓነል",
    "admin.navigateToKeyAreas": "ወደ ቁልፍ አካባቢዎች ይሂዱ",
    "admin.moduleOversight": "የሞጁል ቁጥጥር",
    "admin.statusAcrossStreams": "ሁኔታ ከሦስቱም ዥረቶች",
    "admin.systemWideActivity": "የስርዓት-አቀፍ እንቅስቃሴ",
    "admin.fullReport": "ሙሉ ሪፖርት",
    "admin.technicianWorkload": "የቴክኒሺያን ስራ ጫና",
    "admin.manageUsers": "ተጠቃሚዎችን አስተዳድር",
    "admin.userDistribution": "የተጠቃሚ ስርጭት",
    "admin.allClear": "ሁሉም ግልጽ ነው",
    "admin.workflowAlerts": "የስራ ፍሰት ማሳወቂያዎች",
    "admin.awaitingReview": "ግምግምት ይጠብቃል",
    "admin.unassignedTicket": "ያልተሰጠ ቲኬት",
    "admin.spaceBookingPending": "ቦታ ቅድሚያ በግምገማ ላይ ነው",
    "admin.reviewBtn": "ግምግሙ",
    "admin.assignBtn": "ምደባ",
    "admin.approveBtn": "ፀድቅ",
    "admin.noActionsNeeded": "ምንም በሂደት ላይ ድርጊቶች የሉም",
    "admin.onTrack": "በሂደት ላይ",
    "admin.belowTarget": "ከዒላማ በታች",
    "admin.ok": "ጥሩ",
    "admin.urgent": "አስቸኳይ",
    "admin.high": "ከፍተኛ",
    "admin.normal": "መደበኛ",

    // Config Page - Extended
    "config.statusManagement": "የሁኔታ አስተዳደር",
    "config.priorityLevels": "የቅድሚያ ደረጃዎች",
    "config.notificationTemplates": "የማሳወቂያ አብነቶች",
    "config.systemSettings": "የስርዓት ቅንብሮች",
    "config.manageSettings": "ቅንብሮችን፣ ሁኔታዎችን እና አብነቶችን ያስተዳድሩ",
    "config.savedSuccess": "ቅንብሮች ተቀምጠዋል",

    // All Requests Page
    "requests.allUserRequests": "ሁሉም የተጠቃሚ ጥያቄዎች",
    "requests.unifiedView": "ወጥ እይታ ለሁሉም ቀርቧ ጥያቄዎች",
    "requests.searchRequests": "በርዕስ፣ መለያ ወይም ጠያቂ ፈልግ...",
    "requests.allModules": "ሁሉም ሞጁሎች",
    "requests.noRequestsFound": "ጥያቄዎች አልተገኙም",
    "requests.noRequestsMatch": "ምንም ጥያቄዎች ማጣሪያዎን አያሟሉም",
    "requests.submitted": "ቀርቧል",

    // Bookings - Additional keys (am)
    "bookings.confirmDeleteText": "በቋሚነት ሊሰርዙት ምን ነው:",
    "bookings.noSpacesFound": "ምንም ቦታ አልተገኘም",
    "bookings.tryAdjustFilters": "ፍለጋዎን ወይም ማጣሪያዎን ያስተካክሉ",
    "bookings.addFirstSpace": "የመጀመሪያ ቦታ ጨምር",
    "bookings.seats": "መቀመጫ",
    "bookings.bookNow": "አሁን ያዝ",
    "bookings.currentlyBooked": "አሁን ተይዟል",
    "bookings.step.classification": "ምደባ",
    "bookings.step.officeDetails": "የቢሮ ዝርዝሮች",
    "bookings.step.staffingReqs": "ሰራተኞችና መስፈርቶች",
    "bookings.step.review": "ግምግሙ",
    "bookings.step.selectSpace": "ቦታ ምረጥ",
    "bookings.step.dateTime": "ቀንና ሰዓት",
    "bookings.step.eventDetails": "የዝግጅት ዝርዝሮች",
    "bookings.allocationBeingReviewed": "የቢሮ ቦታ ምደባ ጥያቄዎ በቦታ አስተዳዳሪ ይገምገማል።",
    "bookings.hallPendingApproval": "የአዳራሽ ቅድሚያ ጥያቄዎ በግምገማ ላይ ነው።",
    "bookings.generatedAllocationID": "የተፈጠረ የምደባ መለያ",
    "bookings.generatedBookingID": "የተፈጠረ የቅድሚያ መለያ",
    "bookings.officeAllocationDetails": "የቢሮ ምደባ ዝርዝሮች",
    "bookings.requestingDeptReq": "ጠያቂ ክፍል *",
    "bookings.contactPersonReq": "ተገናኝ ሰው *",
    "bookings.contactPhoneReq": "ተገናኝ ስልክ *",
    "bookings.reasonForAllocReq": "የምደባ ምክንያት *",
    "bookings.officeTypePrefReq": "የቢሮ ዓይነት ምርጫ *",
    "bookings.preferredLocationOpt": "ተፈላጊ አካባቢ (አማራጭ)",
    "bookings.staffingDataTitle": "የሰራተኞች መረጃና ልዩ መስፈርቶች",
    "bookings.seniorStaffCount": "ከፍተኛ ሰራተኞች ቁጥር *",
    "bookings.supportStaffCount": "ደጋፊ ሰራተኞች ቁጥር",
    "bookings.totalHeadcountLabel": "ጠቅላላ ሰዎች:",
    "bookings.people": "ሰዎች",
    "bookings.specialReqsLabel": "ልዩ መስፈርቶች",
    "bookings.additionalNotesLabel": "ተጨማሪ ማስታወሻዎች",
    "bookings.selectASpace": "ቦታ ይምረጡ",
    "bookings.available_dot": "● ያለ",
    "bookings.booked_dot": "● ተይዟል",
    "bookings.capacityCap": "አቅ.",
    "bookings.conflictDetected": "⚠️ ግጭት ተገኝቷል! ይህ ቦታ ለተመረጠው ቀን/ሰዓት ተይዟል።",
    "bookings.dateReq": "ቀን *",
    "bookings.startTimeReq": "የጀመሪያ ሰዓት *",
    "bookings.endTimeReq": "የማብቂያ ሰዓት *",
    "bookings.selectedSpaceLabel": "ተመርጧል:",
    "bookings.capacityDetailLabel": "አቅም:",
    "bookings.eventMeetingTitle": "የዝግጅት / ስብሰባ ርዕስ *",
    "bookings.purposeReq": "ዓላማ *",
    "bookings.numAttendeesReq": "የተሳታፊዎች ብዛት *",
    "bookings.capacityUsed": "ጥቅም ላይ የዋለ አቅም",
    "bookings.roomLayoutLabel": "የክፍል አቀማመጥ",
    "bookings.requiredAmenities": "የሚያስፈልጉ ምቾቶች",
    "bookings.reviewConfirmH2": "ይገምግሙ እና ያረጋግጡ",
    "bookings.b1RequestType": "B1 – የቢሮ ቦታ ምደባ",
    "bookings.b2RequestType": "B2 – የጋራ አዳራሽ ቅድሚያ",
    "bookings.requestTypeKey": "የጥያቄ ዓይነት",
    "bookings.reasonKey": "ምክንያት",
    "bookings.officeTypeKey": "የቢሮ ዓይነት",
    "bookings.seniorStaffKey": "ከፍተኛ ሰራተኞች",
    "bookings.supportStaffKey": "ደጋፊ ሰራተኞች",
    "bookings.totalHeadcountKey": "ጠቅላላ ሰዎች",
    "bookings.specialReqsKey": "ልዩ መስፈርቶች",
    "bookings.preferredLocationKey": "ተፈላጊ አካባቢ",
    "bookings.noPreference": "ምርጫ የለም",
    "bookings.spaceKey": "ቦታ",
    "bookings.timeKey": "ሰዓት",
    "bookings.eventTitleKey": "ርዕስ",
    "bookings.attendeesKey": "ተሳታፊዎች",
    "bookings.layoutKey": "አቀማመጥ",
    "bookings.amenitiesKey": "ምቾቶች",
    "bookings.notSpecified": "አልተጠቀሰም",
    "bookings.noneText": "ምንም",
    "bookings.confirmAndSubmit": "አረጋግጥ እና አቅርብ",
    "bookings.continueBtn": "ቀጥል",
    "bookings.b1CardTitle": "የቢሮ ቦታ ምደባ",
    "bookings.b1CardDesc":
      "ለአዲስ ሰራተኛ፣ ቡድን ማስፋፊያ ወይም ቦታ ቀያሪ። ወደ ቦታ አስተዳዳሪ ይሄዳል።",
    "bookings.b2CardTitle": "የጋራ አዳራሽ / ክፍል ቅድሚያ",
    "bookings.b2CardDesc":
      "የስብሰባ አዳራሾችን፣ ስልጠና ክፍሎችን፣ ላብ ያዙ። ወደ አዳራሽ አስተዳዳሪ ይሄዳል።",

    // Reports - Additional (am)
    "reports.trendPlusTwo": "+2 በዚህ ወር",
    "reports.trendMTTR": "-3ሰ. ካለፈው",
    "reports.trendBudget": "+12%",
    "reports.trendBookings": "+5 በዚህ ሳምንት",

    // Users - Additional (am)
    "users.locked": "ተቆልፏል",

    // All Requests - Additional (am)
    "requests.needsAttention": "ትኩረት ያስፈልጋል",
    "requests.adminNote": "የአስተዳዳሪ ማስታወሻ ለጠያቂው",
    "requests.adminNotePlaceholder": "ማስታወሻ፣ ግብረ-መልስ ወይም ጥያቄ ይጻፉ...",
    "requests.noteSent": "ማስታወሻ ለጠያቂው ተልኳል",
    "requests.sendNote": "ማስታወሻ ላክ",
    "requests.openFullDetail": "ሙሉ ዝርዝር ክፈት",
    "requests.allUsersOption": "ሁሉም ተጠቃሚዎች",
    "requests.requester": "ጠያቂ",
    "requests.sortModule": "ሞጁል",
    "requests.requestsCount": "ጥያቄዎች",
    "requests.filtersBtn": "ማጣሪያዎች",
    "requests.sortDate": "ቀን",
    "requests.sortStatus": "ሁኔታ",
    "requests.sortRequester": "ጠያቂ",

    // Config - Additional (am)
    "config.streamA": "A – ፕሮጀክቶች",
    "config.streamB": "B – ቅድሚያዎች",
    "config.streamC": "C – ጥገና",
    "config.addStatus": "ሁኔታ ጨምር",
    "config.saveChanges": "ለውጦችን አስቀምጥ",
    "config.priorityLevelConfig": "የቅድሚያ ደረጃ ማዋቀር",
    "config.slaTarget": "SLA ዒላማ:",
    "config.colorLabel": "ቀለም",
    "config.savePrioritySettings": "የቅድሚያ ቅንብሮችን አስቀምጥ",
    "config.addTemplate": "አብነት ጨምር",
    "config.saveAllTemplates": "ሁሉንም አብነቶች አስቀምጥ",
    "config.featureToggles": "ባህሪ ቅናሾች",
    "config.adminEmail": "የአስተዳዳሪ ኢሜይል",
    "config.maxFileSize": "ከፍተኛ የፋይል መጠን (MB)",
    "config.sessionTimeout": "የክፍለ ጊዜ ጊዜ ወሰን (ሰዓታት)",
    "config.saveGeneralSettings": "አጠቃላይ ቅንብሮችን አስቀምጥ",
    "config.saveFeatureSettings": "የባህሪ ቅንብሮችን አስቀምጥ",
    "config.enableInAppNotif": "ውስጣዊ ማሳወቂያዎችን አንቃ",
    "config.showNotifBellDesc": "የማሳወቂያ ደወልና ማሳወቂያዎችን አሳይ",
    "config.enableEmailAlerts": "የኢሜይል ማሳወቂያዎችን አንቃ",
    "config.sendEmailStatusDesc": "በሁኔታ ለውጥ ኢሜይል ላክ",
    "config.enableSMSAlerts": "SMS ማሳወቂያዎችን አንቃ",
    "config.sendSMSCriticalDesc": "ወሳኝ ክስተቶች SMS ላክ",
    "config.autoAssignTech": "ቴክኒሺያኖችን ራሱ ምደባ",
    "config.autoAssignDesc": "በተገኝነት ላይ ተመስርቶ ራሱ ምደባ",
    "config.requireBudgetProj": "ለፕሮጀክቶች በጀት ያስፈልጋል",
    "config.requireBudgetDesc": "የበጀት ሜዳ አስፈላጊ ያድርጉ",
  },
} as any as Translations;
